edition = 1
exports = []

[package]
name = "echo-real-server"
manufacturer = "acme"
type = "echo-real-server-service"
description = "An Actor-RTC service"
authors = []

[dependencies]

[system.signaling]
url = "ws://localhost:8081/"

[system.deployment]
realm = 1001

[system.discovery]
visible = true

[scripts]
dev = "cargo run"
test = "cargo test"
