// ── Proto-generated types ────────────────────────────────────────────────────
mod echo {
    include!(concat!(env!("OUT_DIR"), "/echo.rs"));
}

// ── actr-gen output ──────────────────────────────────────────────────────────
//
// `echo_actor.rs` is generated by `protoc-gen-actrframework` from `echo.proto`.
// It defines:
//   - `RpcRequest` impl for `EchoRequest`
//   - `EchoServiceHandler` trait  (you implement this)
//   - `EchoServiceDispatcher<T>`  (generated router, zero-sized type)
//   - `EchoServiceWorkload<T>`    (generated wrapper, satisfies orphan rules)
//   - `impl Workload for EchoServiceWorkload<T>`
#[allow(dead_code)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/echo_actor.rs"));
}

use actr_framework::{Context, entry};
use actr_protocol::ActorResult;
use async_trait::async_trait;

use echo::{EchoRequest, EchoResponse};
#[allow(unused_imports)]
use generated::{EchoServiceHandler, EchoServiceWorkload};

// ── Business logic ───────────────────────────────────────────────────────────

/// Concrete implementation of the EchoService.
///
/// This is the only type you need to write. Add your state here and implement
/// [`EchoServiceHandler`] to provide the actual RPC logic.
pub struct EchoService;

#[async_trait]
impl EchoServiceHandler for EchoService {
    async fn echo<C: Context>(&self, req: EchoRequest, _ctx: &C) -> ActorResult<EchoResponse> {
        Ok(EchoResponse {
            reply: format!("Echo: {}", req.message),
            timestamp: current_timestamp(),
        })
    }
}

// ── Entry point ──────────────────────────────────────────────────────────────

entry!(
    EchoServiceWorkload<EchoService>,
    EchoServiceWorkload::new(EchoService)
);

// ── Platform helpers ─────────────────────────────────────────────────────────

#[cfg(target_arch = "wasm32")]
#[allow(dead_code)]
fn current_timestamp() -> u64 {
    0
}

#[cfg(not(target_arch = "wasm32"))]
#[allow(dead_code)]
fn current_timestamp() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}
