//! Echo Server Guest WASM for Web — unified source (Option U γ-unified Phase 6c).
//!
//! One source tree, two wasm32 ABIs:
//!
//!   * **default**  → `wasm32-wasip2` + wasm-component-ld. The
//!     `actr_framework::entry!` macro's Component Model arm emits the
//!     17-method `Guest` impl that wit-bindgen expects, and the linker
//!     wraps the cdylib into a Component binary.
//!   * **`--features web`** → `wasm32-unknown-unknown` + wasm-pack. The
//!     same `entry!` macro's `cfg(feature = "web")` arm instead emits a
//!     `#[wasm_bindgen(start)]` bootstrap that wraps the workload in
//!     `actr_framework::web::WebWorkloadAdapter` and registers it with
//!     `actr_web_abi::host::register_workload`.
//!
//! The user code below is identical in both branches — target and
//! feature selection happens entirely inside the macro.
//!
//! `cargo build --target wasm32-wasip2` produces a Component Model binary
//! consumed by the native wasmtime host (see core/hyper). Browser-side
//! consumption goes through the `--features web` build instead — the
//! Component Model + jco transpile path was deleted in Option U Phase 8.

// ── Proto-generated types ────────────────────────────────────────────────────
mod echo {
    include!(concat!(env!("OUT_DIR"), "/echo.rs"));
}

// ── actr-gen output ──────────────────────────────────────────────────────────
//
// `echo_actor.rs` is generated by `protoc-gen-actrframework` from `echo.proto`.
// It defines:
//   - `RpcRequest` impl for `EchoRequest`
//   - `EchoServiceHandler` trait  (you implement this)
//   - `EchoServiceDispatcher<T>`  (generated router, zero-sized type)
//   - `EchoServiceWorkload<T>`    (generated wrapper, satisfies orphan rules)
//   - `impl Workload for EchoServiceWorkload<T>`
#[allow(dead_code)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/echo_actor.rs"));
}

use actr_framework::{Context, entry};
use actr_protocol::ActorResult;
use async_trait::async_trait;

use echo::{EchoRequest, EchoResponse};
#[allow(unused_imports)]
use generated::{EchoServiceHandler, EchoServiceWorkload};

// ── Business logic ───────────────────────────────────────────────────────────

/// Concrete implementation of the EchoService.
///
/// Stateless. `Clone` is required by
/// `actr_framework::web::WebWorkloadAdapter`'s `W: Clone` bound under the
/// `web` feature — and comes for free for a zero-field struct. The CM
/// path never clones the workload, so the bound is a no-op there.
#[derive(Clone, Default)]
pub struct EchoService;

// `?Send` on wasm32 so the generated `EchoServiceHandler` trait (whose
// async methods are `async_trait(?Send)` on wasm32 per γ-unified §3.1)
// and this impl agree on the future's auto-trait. Native builds keep
// the default Send-future form.
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
impl EchoServiceHandler for EchoService {
    async fn echo<C: Context>(&self, req: EchoRequest, _ctx: &C) -> ActorResult<EchoResponse> {
        log::info!("📨 Echo request message='{}'", req.message);
        let reply = format!("Echo: {}", req.message);
        log::info!("📤 Echo response reply='{}'", reply);
        Ok(EchoResponse {
            reply,
            timestamp: current_timestamp(),
        })
    }
}

// ── Clone shim for the generated wrapper ─────────────────────────────────────
//
// `protoc-gen-actrframework` emits `pub struct EchoServiceWorkload<T>(pub T)`
// without deriving `Clone`. `WebWorkloadAdapter` requires `W: Workload + Clone`,
// so we bolt `Clone` on from the consuming crate — legal because the type is
// generated into our own module via `include!(...)`. CM builds never call
// `.clone()` on the wrapper; the impl is strictly a web-path prerequisite.
impl<T: EchoServiceHandler + Clone> Clone for EchoServiceWorkload<T> {
    fn clone(&self) -> Self {
        Self(self.0.clone())
    }
}

// ── Entry point ──────────────────────────────────────────────────────────────

entry!(
    EchoServiceWorkload<EchoService>,
    EchoServiceWorkload::new(EchoService)
);

// ── Platform helpers ─────────────────────────────────────────────────────────

#[cfg(target_arch = "wasm32")]
#[allow(dead_code)]
fn current_timestamp() -> u64 {
    0
}

#[cfg(not(target_arch = "wasm32"))]
#[allow(dead_code)]
fn current_timestamp() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}
