//! Echo Server Guest WASM for Web.
//!
//! Built for `wasm32-wasip2` and linked by `wasm-component-ld` into a
//! Component Model binary that implements the `actr:workload/actr-workload-guest`
//! world (see `core/framework/wit/actr-workload.wit`). The `entry!` macro
//! auto-selects the Component Model export path for `target_arch = "wasm32"`,
//! so the source below is identical to a native actr workload.
//!
//! After `cargo build --target wasm32-wasip2`, the resulting
//! `target/wasm32-wasip2/release/echo_guest.wasm` is a Component and must be
//! transpiled by `jco transpile --instantiation async`
//! (see `bindings/web/scripts/transpile-component.sh`) before the browser
//! Service Worker can load it.

// ── Proto-generated types ────────────────────────────────────────────────────
mod echo {
    include!(concat!(env!("OUT_DIR"), "/echo.rs"));
}

// ── actr-gen output ──────────────────────────────────────────────────────────
//
// `echo_actor.rs` is generated by `protoc-gen-actrframework` from `echo.proto`.
// It defines:
//   - `RpcRequest` impl for `EchoRequest`
//   - `EchoServiceHandler` trait  (you implement this)
//   - `EchoServiceDispatcher<T>`  (generated router, zero-sized type)
//   - `EchoServiceWorkload<T>`    (generated wrapper, satisfies orphan rules)
//   - `impl Workload for EchoServiceWorkload<T>`
#[allow(dead_code)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/echo_actor.rs"));
}

use actr_framework::{Context, entry};
use actr_protocol::ActorResult;
use async_trait::async_trait;

use echo::{EchoRequest, EchoResponse};
#[allow(unused_imports)]
use generated::{EchoServiceHandler, EchoServiceWorkload};

// ── Business logic ───────────────────────────────────────────────────────────

/// Concrete implementation of the EchoService.
///
/// This is the only type you need to write. Add your state here and implement
/// [`EchoServiceHandler`] to provide the actual RPC logic.
pub struct EchoService;

// `?Send` on wasm32 so the generated `EchoServiceHandler` trait (whose
// async methods are now `async_trait(?Send)` on wasm32 per γ-unified
// §3.1) and this impl agree on the future's auto-trait. Native builds
// keep the default Send-future form.
#[cfg_attr(not(target_arch = "wasm32"), async_trait)]
#[cfg_attr(target_arch = "wasm32", async_trait(?Send))]
impl EchoServiceHandler for EchoService {
    async fn echo<C: Context>(&self, req: EchoRequest, _ctx: &C) -> ActorResult<EchoResponse> {
        Ok(EchoResponse {
            reply: format!("Echo: {}", req.message),
            timestamp: current_timestamp(),
        })
    }
}

// ── Entry point ──────────────────────────────────────────────────────────────

entry!(
    EchoServiceWorkload<EchoService>,
    EchoServiceWorkload::new(EchoService)
);

// ── Platform helpers ─────────────────────────────────────────────────────────

#[cfg(target_arch = "wasm32")]
#[allow(dead_code)]
fn current_timestamp() -> u64 {
    0
}

#[cfg(not(target_arch = "wasm32"))]
#[allow(dead_code)]
fn current_timestamp() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}
