edition = 1

[package]
path = "release/acme-EchoService-0.1.0-wasm32-unknown-unknown.actr"

[signaling]
url = "ws://localhost:8081/signaling/ws"

[ais_endpoint]
url = "http://localhost:8081/ais"

[deployment]
realm_id = 2368266035


[discovery]
visible = true

[observability]
filter_level = "info"
tracing_enabled = false

[webrtc]
force_relay = false
stun_urls = ["stun:localhost:3478"]
turn_urls = ["turn:localhost:3478"]

[acl]

[[acl.rules]]
permission = "allow"
type = "acme:echo-client-app:0.1.0"

[web]
port = 5174
host = "0.0.0.0"

[[trust]]
kind = "static"
pubkey_b64 = "__MFR_PUBKEY_PLACEHOLDER__"
