edition = 1
exports = ["../proto/echo.proto"]

[package]
name = "EchoService"
manufacturer = "acme"
version = "1.0.0"
description = "Echo Real Server"
authors = ["Actr Dev Team"]
license = "Apache-2.0"
tags = ["dev", "example"]

[dependencies]

[system.signaling]
url = "ws://localhost:8081/signaling/ws"

[system.ais_endpoint]
url = "http://localhost:8081/ais"

[system.deployment]
realm_id = 759049003
realm_secret = "rs_AclExampleSecret123456"


[system.discovery]
visible = true

[system.observability]
filter_level = "info"
tracing_enabled = false
tracing_endpoint = "http://localhost:4317"
tracing_service_name = "echo-real-server"

[system.webrtc]
force_relay = false
stun_urls = ["stun:localhost:3478"]
turn_urls = ["turn:localhost:3478"]

# ACL configuration - allow echo client
[acl]

[[acl.rules]]
permission = "allow"
# Allow clients with actr_type = "acme:echo-client-app:1.0.0"
type = "acme:echo-client-app:1.0.0"

[scripts]
dev = "cargo run"
test = "cargo test"
