/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const init: () => void;
export const register_echo_service: () => void;
export const handle_dom_control: (a: number, b: number, c: any) => any;
export const handle_dom_fast_path: (a: number, b: number, c: any) => [number, number];
export const handle_dom_webrtc_event: (a: number, b: number, c: any) => any;
export const init_global: () => [number, number];
export const register_client: (a: number, b: number, c: any, d: any) => any;
export const register_datachannel_port: (a: number, b: number, c: number, d: number, e: any) => any;
export const unregister_client: (a: number, b: number) => any;
export const wasm_bindgen__closure__destroy__h5a05f2a88d4b9300: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hff5f1365318bebd6: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h329e548a2f539608: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h2bf42a8b2ffdb9c9: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hf5ee9d21c8541ba9: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h4fb9192c223e57b8: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h263251508bdf13c3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h263251508bdf13c3_1: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h263251508bdf13c3_2: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h263251508bdf13c3_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h263251508bdf13c3_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h4b2b0d0c520d2fe0: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h9584e8edcc7fcc5d: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
