//! WASM Guest-Host ABI definitions and `entry!` macro
//!
//! This module defines:
//! 1. **ABI error codes**: kept in sync with `actr-runtime`'s `wasm/abi.rs`
//! 2. **`entry!` macro**: generates all necessary WASM ABI export functions for a Workload type
//!
//! # ABI export functions (generated by `entry!` macro)
//!
//! ```text
//! // Allocate WASM linear memory (host calls before writing data)
//! actr_alloc(size: i32) -> i32
//!
//! // Free WASM linear memory (host calls after read/write is done)
//! actr_free(ptr: i32, size: i32)
//!
//! // Initialize actor (host calls before first actr_handle call)
//! // config_ptr/len: JSON-encoded WasmActorConfig
//! // Returns: 0 on success, -2 on failure
//! actr_init(config_ptr: i32, config_len: i32) -> i32
//!
//! // Handle one RPC request
//! // req_ptr/len: protobuf-encoded RpcEnvelope
//! // resp_ptr_out: host-provided i32* pointer, WASM writes response buffer address here
//! // resp_len_out: host-provided i32* pointer, WASM writes response data length here
//! // Returns: 0 on success, < 0 error code
//! actr_handle(req_ptr: i32, req_len: i32, resp_ptr_out: i32, resp_len_out: i32) -> i32
//! ```
//!
//! # Usage example
//!
//! ```rust,ignore
//! use actr_runtime_wasm::entry;
//!
//! struct MyService;
//! // impl EchoServiceHandler for MyService { ... }
//!
//! // Use Default initialization (requires MyWorkload: Default)
//! entry!(EchoServiceWorkload<MyService>);
//!
//! // Or provide a custom initialization expression
//! entry!(EchoServiceWorkload<MyService>, EchoServiceWorkload(MyService::new()));
//! ```

/// ABI error codes (kept in sync with actr-runtime::wasm::abi::code)
pub mod code {
    pub const SUCCESS: i32 = 0;
    pub const GENERIC_ERROR: i32 = -1;
    pub const INIT_FAILED: i32 = -2;
    pub const HANDLE_FAILED: i32 = -3;
    pub const ALLOC_FAILED: i32 = -4;
    pub const PROTOCOL_ERROR: i32 = -5;
}

/// Generate WASM ABI export functions for a Workload type
///
/// # Arguments
///
/// - `$workload_type`: Type implementing `actr_framework::Workload + Send + Sync + 'static`
/// - `$init_expr` (optional): Expression to construct the Workload instance; uses `Default::default()` if omitted
///
/// # Generated exports
///
/// - `actr_alloc(size: i32) -> i32`
/// - `actr_free(ptr: i32, size: i32)`
/// - `actr_init(config_ptr: i32, config_len: i32) -> i32`
/// - `actr_handle(req_ptr: i32, req_len: i32, resp_ptr_out: i32, resp_len_out: i32) -> i32`
#[macro_export]
macro_rules! entry {
    // Single-argument form: use Default::default() for initialization
    ($workload_type:ty) => {
        $crate::entry!($workload_type, <$workload_type as Default>::default());
    };

    // Two-argument form: use custom initialization expression
    ($workload_type:ty, $init_expr:expr) => {
        // WASM is single-threaded, static mut access is safe
        static mut __ACTR_WORKLOAD: Option<$workload_type> = None;

        /// Allocate WASM linear memory (host calls before writing data)
        #[unsafe(no_mangle)]
        pub extern "C" fn actr_alloc(size: i32) -> i32 {
            let layout =
                std::alloc::Layout::from_size_align(size as usize, 1).expect("invalid layout");
            let ptr = unsafe { std::alloc::alloc(layout) };
            if ptr.is_null() {
                $crate::abi::code::ALLOC_FAILED
            } else {
                ptr as i32
            }
        }

        /// Free WASM linear memory (host calls after read/write is done)
        #[unsafe(no_mangle)]
        pub extern "C" fn actr_free(ptr: i32, size: i32) {
            if ptr == 0 || size <= 0 {
                return;
            }
            let layout =
                std::alloc::Layout::from_size_align(size as usize, 1).expect("invalid layout");
            unsafe { std::alloc::dealloc(ptr as *mut u8, layout) };
        }

        /// Initialize actor (host calls before first actr_handle call)
        ///
        /// `config_ptr/len`: JSON-encoded WasmActorConfig (reserved for future extension)
        #[unsafe(no_mangle)]
        pub extern "C" fn actr_init(_config_ptr: i32, _config_len: i32) -> i32 {
            let workload: $workload_type = $init_expr;
            unsafe {
                __ACTR_WORKLOAD = Some(workload);
            }
            $crate::abi::code::SUCCESS
        }

        /// Handle one RPC request
        ///
        /// - `req_ptr/len`: protobuf-encoded `RpcEnvelope`
        /// - `resp_ptr_out`: host-provided `i32*`, WASM writes response buffer address here
        /// - `resp_len_out`: host-provided `i32*`, WASM writes response data length here
        #[unsafe(no_mangle)]
        pub extern "C" fn actr_handle(
            req_ptr: i32,
            req_len: i32,
            resp_ptr_out: i32,
            resp_len_out: i32,
        ) -> i32 {
            use actr_framework::{MessageDispatcher, Workload};
            use actr_protocol::prost::Message as ProstMessage;

            // Read request envelope
            let req_bytes: &[u8] =
                unsafe { std::slice::from_raw_parts(req_ptr as *const u8, req_len as usize) };

            let envelope = match actr_protocol::RpcEnvelope::decode(req_bytes) {
                Ok(e) => e,
                Err(_) => return $crate::abi::code::PROTOCOL_ERROR,
            };

            // Build WasmContext (obtain current call context data from host)
            let ctx = match $crate::context::WasmContext::from_host() {
                Ok(c) => c,
                Err(_) => return $crate::abi::code::HANDLE_FAILED,
            };

            // Get workload reference
            let workload = unsafe {
                match __ACTR_WORKLOAD.as_ref() {
                    Some(w) => w,
                    None => return $crate::abi::code::INIT_FAILED,
                }
            };

            // Route and execute via MessageDispatcher
            type Dispatcher = <$workload_type as Workload>::Dispatcher;
            let resp_result =
                $crate::executor::block_on(Dispatcher::dispatch(workload, envelope, &ctx));

            let resp_bytes = match resp_result {
                Ok(b) => b,
                Err(_) => return $crate::abi::code::HANDLE_FAILED,
            };

            // Allocate response buffer in WASM linear memory, return to host
            let resp_len = resp_bytes.len();
            let layout =
                std::alloc::Layout::from_size_align(resp_len.max(1), 1).expect("invalid layout");
            let resp_ptr = unsafe { std::alloc::alloc(layout) };
            if resp_ptr.is_null() {
                return $crate::abi::code::ALLOC_FAILED;
            }

            // Write response data to WASM linear memory
            unsafe {
                std::ptr::copy_nonoverlapping(resp_bytes.as_ptr(), resp_ptr, resp_len);
                // Write response buffer address and length to host-provided output pointers
                *(resp_ptr_out as *mut i32) = resp_ptr as i32;
                *(resp_len_out as *mut i32) = resp_len as i32;
            }

            $crate::abi::code::SUCCESS
        }
    };
}
