//! WASM single-threaded Future executor
//!
//! WASM is a single-threaded environment; actor business code achieves transparent
//! host import suspend/resume via asyncify. From the Rust Future perspective,
//! all calls complete synchronously (a single poll returns `Ready`).
//!
//! # How it works
//!
//! When `WasmContext::call(...)` calls `actr_host_call` host import:
//! 1. **Normal mode**: Host calls `asyncify_start_unwind`, WASM saves the entire call stack (including this executor's stack frame) then returns
//! 2. **Rewinding mode**: Host calls `asyncify_start_rewind` then re-enters WASM, resuming from the saved point
//! 3. Host import returns the actual IO result on the rewind path, Future continues executing until `Poll::Ready`
//!
//! Therefore, `poll` will only return `Poll::Ready`; `Poll::Pending` indicates a program error.

use std::future::Future;
use std::pin::Pin;
use std::task::{Context, Poll, RawWaker, RawWakerVTable, Waker};

/// Synchronously drive a Future to completion in WASM single-threaded environment
///
/// # Panics
///
/// Panics if the Future returns `Poll::Pending` (should not happen).
/// All `.await` points in business code are transparently handled by asyncify and will not produce real Pending.
pub fn block_on<F: Future>(f: F) -> F::Output {
    let mut f = std::pin::pin!(f);
    let waker = noop_waker();
    let mut cx = Context::from_waker(&waker);

    match f.as_mut().poll(&mut cx) {
        Poll::Ready(v) => v,
        Poll::Pending => {
            // This should not happen: WASM + asyncify guarantees all await points complete synchronously
            panic!(
                "Future returned Pending in WASM environment; ensure all await points are processed via asyncify"
            )
        }
    }
}

// -- Noop Waker -------------------------------------------------------------------

/// Construct a no-op Waker
///
/// The WASM executor does not need wake notifications -- the Future always completes on first poll.
fn noop_waker() -> Waker {
    const VTABLE: RawWakerVTable = RawWakerVTable::new(
        |p| RawWaker::new(p, &VTABLE), // clone
        |_| {},                        // wake
        |_| {},                        // wake_by_ref
        |_| {},                        // drop
    );
    unsafe { Waker::from_raw(RawWaker::new(std::ptr::null(), &VTABLE)) }
}

// -- Helper: synchronously execute Pin<Box<dyn Future>> ----------------------------

/// Synchronously execute `Pin<Box<dyn Future<Output = T> + Send>>`
///
/// Used to execute boxed futures generated by `#[async_trait]`.
pub fn block_on_boxed<T>(f: Pin<Box<dyn Future<Output = T> + Send>>) -> T {
    block_on(f)
}
