[package]
name = "EchoService"
manufacturer = "acme"
version = "0.1.0"
description = "Echo Server - Browser-side Actor Service"
authors = ["Actr Dev Team"]
license = "Apache-2.0"
tags = ["dev", "server"]
exports = ["../proto/echo.proto"]
