/**
 * Kotlin Actor Code Generator
 *
 * Generates Handler interface and Dispatcher for ACTR services. Similar to the Rust ModernGenerator
 * but for Kotlin.
 */
package io.actrium.codegen

import com.google.protobuf.DescriptorProtos.MethodDescriptorProto
import com.google.protobuf.compiler.PluginProtos.CodeGeneratorResponse

private const val ACTR_PAYLOAD_TYPE_FIELD_NUMBER = 50001

private enum class RpcPayloadType(val protoValue: Long, val kotlinVariant: String) {
    RPC_RELIABLE(0, "PayloadType.RPC_RELIABLE"),
    RPC_SIGNAL(1, "PayloadType.RPC_SIGNAL"),
    STREAM_RELIABLE(2, "PayloadType.STREAM_RELIABLE"),
    STREAM_LATENCY_FIRST(3, "PayloadType.STREAM_LATENCY_FIRST"),
    MEDIA_RTP(4, "PayloadType.MEDIA_RTP");

    companion object {
        fun fromProtoValue(value: Long): RpcPayloadType? =
                entries.firstOrNull { it.protoValue == value }
    }
}

/** Declaring owner of a proto message type and its generated JVM shape. */
data class TypeOwner(
        val packageName: String,
        val protoFileName: String,
        val javaPackage: String = "",
        val javaOuterClassName: String = "",
        val javaMultipleFiles: Boolean = false,
        val messagePath: List<String> = emptyList(),
)

/** Generator for Kotlin Actor framework code */
class KotlinActorGenerator(
        private val packageName: String,
        private val serviceName: String,
        private val methods: List<MethodDescriptorProto>,
        private val params: Map<String, String>,
        private val protoFileName: String = "",
        private val typeOwner: Map<String, TypeOwner> = emptyMap()
) {
    /** Generate the actor code file */
    fun generate(): CodeGeneratorResponse.File {
        val kotlinPackage = params["kotlin_package"] ?: "com.example.generated"
        val code = buildString {
            appendLine(generateHeader(kotlinPackage))
            appendLine()
            appendLine(generateImports())
            appendLine()
            appendLine(generateHandlerInterface())
            appendLine()
            appendLine(generateRpcContracts())
            appendLine()
            appendLine(generateDispatcher())
        }

        val fileName = "${serviceName.toSnakeCase()}_actor.kt"

        return CodeGeneratorResponse.File.newBuilder().setName(fileName).setContent(code).build()
    }

    /** Generate file header */
    private fun generateHeader(kotlinPackage: String): String {
        return """
            |/**
            | * Auto-generated code - DO NOT EDIT
            | *
            | * Generated by protoc-gen-actrframework-kotlin plugin
            | *
            | * Service: $serviceName
            | * Package: $packageName
            | */
            |package $kotlinPackage
        """.trimMargin()
    }

    /** Generate import statements */
    private fun generateImports(): String {
        return buildString {
            appendLine("import io.actrium.actr.PayloadType")
            appendLine("import io.actrium.actr.dsl.ActrContext")
            appendLine("import io.actrium.actr.dsl.RpcRequest")
            appendLine("import io.actrium.actr.dsl.RpcEnvelope")
            appendLine()
            appendLine("// Protobuf message types are referenced by generated JVM owner class.")
        }
    }

    /** Resolve the declaring owner for a proto RPC type from the descriptor set. */
    private fun resolveOwner(typeName: String, kind: String, methodName: String): TypeOwner {
        val cleaned = typeName.trimStart('.')
        return typeOwner[cleaned]
                ?: throw IllegalArgumentException(
                        "Cannot resolve $kind type `$cleaned` for $serviceName.$methodName in " +
                                "$protoFileName: RPC types must be declared in one of the parsed proto files")
    }

    /** Java/Kotlin outer class name for a proto file: PascalCase of the file
     * stem (e.g. `ask.proto` -> `Ask`, `data_stream_app.proto` -> `DataStreamApp`). */
    private fun outerClassFor(protoFileName: String): String {
        if (protoFileName.isEmpty()) return ""
        val baseName = protoFileName.substringAfterLast("/").removeSuffix(".proto")
        return baseName.toPascalCase()
    }

    /** Generate Handler interface */
    private fun generateHandlerInterface(): String {
        val handlerName = "${serviceName}Handler"

        val methodSignatures =
                methods.joinToString("\n\n") { method ->
                    val methodName = method.name.toSnakeCase()
                    val inputType = kotlinTypeName(method.inputType, "input", method.name)
                    val outputType = kotlinTypeName(method.outputType, "output", method.name)

                    """
            |    /**
            |     * RPC method: ${method.name}
            |     */
            |    suspend fun $methodName(request: $inputType, ctx: ActrContext): $outputType
            """.trimMargin()
                }

        return """
            |/**
            | * Handler interface for $serviceName
            | *
            | * Implement this interface to provide your business logic.
            | *
            | * Example:
            | * ```kotlin
            | * class My$serviceName : $handlerName {
            | *     override suspend fun methodName(request: RequestType, ctx: ActrContext): ResponseType {
            | *         // Business logic here
            | *         return ResponseType.newBuilder().build()
            | *     }
            | * }
            | * ```
            | */
            |interface $handlerName {
            |$methodSignatures
            |}
        """.trimMargin()
    }

    /** Generate outbound RpcRequest contracts for type-safe remote calls. */
    private fun generateRpcContracts(): String {
        val contracts =
                methods.joinToString("\n\n") { method ->
                    val contractName = rpcContractName(method)
                    val inputType = kotlinTypeName(method.inputType, "input", method.name)
                    val outputType = kotlinTypeName(method.outputType, "output", method.name)
                    val routeKey = routeKey(method)
                    val payloadType = payloadTypeFor(method).kotlinVariant

                    """
            |/**
            | * Type-safe outbound RPC contract for ${method.name}.
            | */
            |object $contractName : RpcRequest<$inputType, $outputType> {
            |    override val routeKey: String = "$routeKey"
            |    override val payloadType: PayloadType = $payloadType
            |
            |    override fun serializeRequest(request: $inputType): ByteArray = request.toByteArray()
            |
            |    override fun deserializeResponse(bytes: ByteArray): $outputType = $outputType.parseFrom(bytes)
            |}
            """.trimMargin()
                }

        return """
            |/**
            | * Type-safe outbound RPC contracts for $serviceName.
            | */
            |$contracts
        """.trimMargin()
    }

    /** Generate Dispatcher object */
    private fun generateDispatcher(): String {
        val dispatcherName = "${serviceName}Dispatcher"
        val handlerName = "${serviceName}Handler"

        val matchCases =
                methods.joinToString("\n") { method ->
                    val routeKey = routeKey(method)
                    val methodName = method.name.toSnakeCase()
                    val inputType = kotlinTypeName(method.inputType, "input", method.name)

                    """
            |            "$routeKey" -> {
            |                val request = $inputType.parseFrom(envelope.payload)
            |                val response = handler.$methodName(request, ctx)
            |                response.toByteArray()
            |            }
            """.trimMargin()
                }

        return """
            |/**
            | * Message dispatcher for $serviceName
            | *
            | * Routes incoming messages to the appropriate handler method.
            | * This is a zero-overhead dispatcher - all routing is done at compile time.
            | */
            |object $dispatcherName {
            |    /**
            |     * Dispatch an RPC envelope to the appropriate handler method
            |     *
            |     * @param handler The handler implementation
            |     * @param ctx The context for making RPC calls
            |     * @param envelope The RPC envelope containing the request
            |     * @return The serialized response bytes
            |     */
            |    suspend fun dispatch(
            |        handler: $handlerName,
            |        ctx: ActrContext,
            |        envelope: RpcEnvelope
            |    ): ByteArray {
            |        return when (envelope.routeKey) {
            |$matchCases
            |            else -> throw io.actrium.actr.ActrException.UnknownRoute("Unknown route key: ${'$'}{envelope.routeKey}")
            |        }
            |    }
            |}
        """.trimMargin()
    }

    private fun routeKey(method: MethodDescriptorProto): String {
        return if (packageName.isEmpty()) {
            "$serviceName.${method.name}"
        } else {
            "$packageName.$serviceName.${method.name}"
        }
    }

    private fun payloadTypeFor(method: MethodDescriptorProto): RpcPayloadType {
        val explicitValue =
                method.options.unknownFields
                        .getField(ACTR_PAYLOAD_TYPE_FIELD_NUMBER)
                        .varintList
                        .firstOrNull()
        if (explicitValue != null) {
            return RpcPayloadType.fromProtoValue(explicitValue)
                    ?: throw IllegalArgumentException(
                            "Unsupported (actr.payload_type) value $explicitValue on ${routeKey(method)}")
        }
        return if (method.clientStreaming || method.serverStreaming) {
            RpcPayloadType.STREAM_RELIABLE
        } else {
            RpcPayloadType.RPC_RELIABLE
        }
    }

    private fun rpcContractName(method: MethodDescriptorProto): String {
        val serviceBase = serviceName.removeSuffix("Service").toPascalCase()
        val methodName = method.name.toPascalCase()
        return "$serviceBase${methodName}Rpc"
    }

    /** Resolve a fully-qualified proto type to the generated JVM type name. */
    fun kotlinTypeName(typeName: String, kind: String, methodName: String): String {
        val cleaned = typeName.trimStart('.')
        val owner = resolveOwner(typeName, kind, methodName)
        val packagePrefix = owner.javaPackage.ifEmpty { owner.packageName }
        val messagePath =
                if (owner.messagePath.isEmpty()) listOf(extractMessageType(cleaned))
                else owner.messagePath
        val classPath =
                if (owner.javaMultipleFiles) {
                    messagePath.joinToString(".")
                } else {
                    val outer = owner.javaOuterClassName.ifEmpty { outerClassFor(owner.protoFileName) }
                    (listOf(outer) + messagePath).filter { it.isNotEmpty() }.joinToString(".")
                }
        return if (packagePrefix.isEmpty()) classPath else "$packagePrefix.$classPath"
    }

    /** Extract message type name from fully qualified proto type. */
    private fun extractMessageType(typeName: String): String {
        val cleaned = typeName.trimStart('.')
        return cleaned.split(".").last()
    }

    /** Convert string to snake_case */
    private fun String.toSnakeCase(): String {
        return this.replace(Regex("(.)([A-Z][a-z]+)"), "$1_$2")
                .replace(Regex("([a-z0-9])([A-Z])"), "$1_$2")
                .lowercase()
    }

    /** Convert string to PascalCase */
    private fun String.toPascalCase(): String {
        return this.split("_", "-").joinToString("") { word ->
            word.replaceFirstChar { it.uppercase() }
        }
    }
}
