[metadata]
version = 1
generated_at = "2026-03-06T02:40:00.000000+00:00"

[[dependency]]
name = "ws-echo-server"
actr_type = "acme:WsEchoService:1.0.0"
fingerprint = "service_semantic:0d0d204d724cafc1cb8fd5d6f68ca683d9f6546c6e70deab75781a2f4230a755"
cached_at = "2026-03-06T02:40:00.000000+00:00"

[[dependency.files]]
path = "ws-echo-server/echo.proto"
fingerprint = ""
