//! WASM Echo Service Guest Actor
//!
//! A simple echo service compiled to wasm32-unknown-unknown and loaded by the
//! host server via the WASM executor adapter. Demonstrates the Actor-RTC WASM
//! execution model: the host drives `actr_handle` through the asyncify ABI,
//! while the guest implements standard `Workload` / `MessageDispatcher` traits.
//!
//! # Protocol
//!
//! - Route key: `echo.EchoService.Echo`
//! - Request:  protobuf `EchoRequest { message: string }`
//! - Response: protobuf `EchoResponse { reply: string, timestamp: uint64 }`

use actr_framework::{Context, MessageDispatcher, Workload, entry};
use actr_protocol::{ActorResult, ActrError, RpcEnvelope};
use async_trait::async_trait;
use bytes::Bytes;
use prost::Message as ProstMessage;

/// Generated protobuf types from echo.proto
mod echo {
    include!(concat!(env!("OUT_DIR"), "/echo.rs"));
}

use echo::{EchoRequest, EchoResponse};

// ── Workload ──────────────────────────────────────────────────────────────────

/// Shell workload type for the WASM echo service
#[derive(Default)]
pub struct EchoServiceWorkload;

/// Static message dispatcher — routes incoming RPC envelopes to the echo handler
pub struct EchoServiceDispatcher;

#[async_trait]
impl MessageDispatcher for EchoServiceDispatcher {
    type Workload = EchoServiceWorkload;

    async fn dispatch<C: Context>(
        _workload: &Self::Workload,
        envelope: RpcEnvelope,
        _ctx: &C,
    ) -> ActorResult<Bytes> {
        match envelope.route_key.as_str() {
            "echo.EchoService.Echo" => {
                let payload = envelope
                    .payload
                    .as_ref()
                    .ok_or_else(|| ActrError::DecodeFailure("Missing payload".into()))?;

                let req = EchoRequest::decode(&**payload)
                    .map_err(|e| ActrError::DecodeFailure(e.to_string()))?;

                let reply = format!("Echo: {}", req.message);

                // Note: wasm32 does not have std::time, so timestamp is always 0.
                let resp = EchoResponse {
                    reply,
                    timestamp: 0,
                };

                Ok(resp.encode_to_vec().into())
            }
            _ => Err(ActrError::UnknownRoute(envelope.route_key)),
        }
    }
}

impl Workload for EchoServiceWorkload {
    type Dispatcher = EchoServiceDispatcher;
}

// ── ABI exports (generated by entry! macro) ──────────────────────────────────

entry!(EchoServiceWorkload);
