#!/bin/bash
set -e

echo "🔨 Building Echo Client WASM..."
echo "   Local handler + SW runtime -> single WASM"

# Ensure a writable temp directory for wasm-bindgen install.
TMPDIR="${TMPDIR:-$(pwd)/.tmp}"
export TMPDIR
mkdir -p "$TMPDIR"

# Output directory (written to client/public)
OUT_DIR="../public"

# Remove previous build output
rm -f "$OUT_DIR"/echo_client*.wasm "$OUT_DIR"/echo_client*.js "$OUT_DIR"/echo_client*.d.ts
# Also remove old bare-runtime files
rm -f "$OUT_DIR"/actr_runtime_sw*.wasm "$OUT_DIR"/actr_runtime_sw*.js

# Build the WASM bundle
# - target: no-modules (fits Service Workers and uses wasm_bindgen globals)
# - includes: SW runtime + local handler (EchoClient proxy)
wasm-pack build \
  --target no-modules \
  --out-dir "$OUT_DIR" \
  --out-name echo_client \
  --release

# Remove files that are not needed
rm -f "$OUT_DIR/package.json" "$OUT_DIR/.gitignore"

echo ""
echo "✅ WASM built successfully!"
echo ""
echo "📁 Output: $OUT_DIR"
echo ""
echo "Artifacts:"
echo "  - echo_client_bg.wasm  : main WASM payload (Local Handler + SW Runtime)"
echo "  - echo_client.js       : JS glue generated by wasm-bindgen"
echo "  - echo_client.d.ts     : TypeScript type definitions"
echo ""
echo "Files:"
ls -la "$OUT_DIR"/echo_client*

echo ""
echo "Next step:"
echo "   1. Start the dev server: cd .. && pnpm dev"
