# SPDX-License-Identifier: Apache-2.0
#
# Python implementation of an actr workload, compiled to wasm32-wasip2
# Component via componentize-py. Demonstrates that the actr:workload
# contract (core/framework/wit/actr-workload.wit) can be authored in
# Python end-to-end.
#
# Semantics: dispatch echoes the incoming payload back with an "echo: "
# prefix. Lifecycle / signaling / transport / credential / mailbox hooks
# are implemented as infallible no-ops (mirrors the Go and C examples).
#
# Module shape (generated by componentize-py):
#
#   componentize-py \
#       -w actr-workload-guest \
#       -d ../../../core/framework/wit/actr-workload.wit \
#       bindings bindings/
#
#   produces under bindings/:
#     actr_workload/__init__.py                — world entry glue
#     actr_workload/exports/__init__.py
#     actr_workload/exports/workload.py        — Workload protocol class
#     actr_workload/imports/__init__.py
#     actr_workload/imports/host.py            — host-side imports
#     actr_workload/types.py                   — record / variant types
#
# The `componentize` subcommand then bundles *this* source file + the
# generated bindings + the CPython WASM interpreter into one Component.
#
# Note: componentize-py is alpha (Bytecode Alliance, 2025-). The exact
# import paths / class names below follow the generator's documented
# convention for `package actr:workload@0.1.0`; if future versions of
# componentize-py adjust the mapping, only the imports need to change —
# the Workload subclass methods match the WIT interface 1:1.

from actr_workload.exports import workload as workload_exports
from actr_workload.types import Err
from actr_workload import exports as _exports  # noqa: F401  (import side-effects)

# RpcEnvelope / PeerEvent / ErrorEvent / CredentialEvent / BackpressureEvent
# are record dataclasses emitted by componentize-py under
# `actr_workload.types`. They are imported lazily inside the methods so
# the module loads even when the bindings are stale.


_ECHO_PREFIX = b"echo: "


class Workload(workload_exports.Workload):
    """Echo workload — implements the `workload` interface from the
    `actr-workload-guest` world.

    The four lifecycle hooks (on-start / on-ready / on-stop / on-error)
    return `None`, which componentize-py encodes as `Ok(())`. Raising
    a wrapped `Err(ActrError)` would surface an error to the host.

    The remaining twelve observation hooks are infallible by WIT and
    simply return None.
    """

    # ── Inbound RPC dispatch ────────────────────────────────────────────
    #
    # WIT: dispatch: func(envelope: rpc-envelope) -> result<list<u8>, actr-error>
    #
    # componentize-py maps `list<u8>` to Python `bytes` on both the input
    # (`envelope.payload`) and the output side. The result variant is
    # handled by returning `bytes` on success, or raising an `Err` that
    # wraps an `ActrError` variant on failure.
    def dispatch(self, envelope) -> bytes:
        payload = envelope.payload if envelope.payload is not None else b""
        return _ECHO_PREFIX + bytes(payload)

    # ── Lifecycle (4, fallible) ─────────────────────────────────────────

    def on_start(self) -> None:
        return None

    def on_ready(self) -> None:
        return None

    def on_stop(self) -> None:
        return None

    def on_error(self, event) -> None:
        return None

    # ── Signaling (3, infallible) ───────────────────────────────────────

    def on_signaling_connecting(self) -> None:
        return None

    def on_signaling_connected(self) -> None:
        return None

    def on_signaling_disconnected(self) -> None:
        return None

    # ── Transport: WebSocket (3, infallible) ────────────────────────────

    def on_websocket_connecting(self, event) -> None:
        return None

    def on_websocket_connected(self, event) -> None:
        return None

    def on_websocket_disconnected(self, event) -> None:
        return None

    # ── Transport: WebRTC (3, infallible) ───────────────────────────────

    def on_webrtc_connecting(self, event) -> None:
        return None

    def on_webrtc_connected(self, event) -> None:
        return None

    def on_webrtc_disconnected(self, event) -> None:
        return None

    # ── Credential (2, infallible) ──────────────────────────────────────

    def on_credential_renewed(self, event) -> None:
        return None

    def on_credential_expiring(self, event) -> None:
        return None

    # ── Mailbox (1, infallible) ─────────────────────────────────────────

    def on_mailbox_backpressure(self, event) -> None:
        return None


# Silence unused-import linting for the `Err` re-export above; downstream
# callers that want to raise structured actr errors import it from this
# module as `from workload import Err`.
__all__ = ["Workload", "Err"]
