edition = 1
exports = []

[package]
name = "echo-client-app"
manufacturer = "acme"
description = "Android Echo Client"
authors = []
license = "Apache-2.0"
tags = ["dev", "example", "android"]

[dependencies]
EchoService = { actr_type = "acme+EchoService" }
DataStreamConcurrentServer = { actr_type = "acme+DataStreamConcurrentServer" }

[system.signaling]
url = "wss://actrix1.develenv.com/signaling/ws"

[system.webrtc]
stun_urls = ["stun:actrix1.develenv.com:3478"]
turn_urls = ["turn:actrix1.develenv.com:3478"]
force_relay = true

[system.deployment]
realm_id = 2368266035

[system.discovery]
visible = true

[system.observability]
filter_level = "info"
tracing_enabled = false
tracing_endpoint = "http://10.30.3.206:4317"
tracing_service_name = "android-echo-client"

# ACL configuration
[acl]

[[acl.rules]]
permission = "allow"
types = ["acme+EchoService", "acme+DataStreamConcurrentServer"]

[scripts]
