[metadata]
version = 1
generated_at = "2026-02-10T07:05:55.147116+00:00"

[[dependency]]
name = "data-stream-peer-concurrent-server-python"
actr_type = "acme+DataStreamConcurrentServer"
fingerprint = "service_semantic:bb9bbcedbfb58dbca4989d56d58d4c7f638eccd66185655792104542164d52df"
cached_at = "2026-02-10T07:05:55.147109+00:00"

[[dependency.files]]
path = "data-stream-peer-concurrent-server-python/data_stream_peer.proto"
fingerprint = ""

[[dependency]]
name = "echo-echo-server"
actr_type = "acme+EchoService"
fingerprint = "service_semantic:0d0d204d724cafc1cb8fd5d6f68ca683d9f6546c6e70deab75781a2f4230a755"
cached_at = "2026-02-10T07:05:55.147114+00:00"

[[dependency.files]]
path = "echo-echo-server/echo.proto"
fingerprint = ""
