from __future__ import annotations

from typing import Any, Protocol


class Workload(Protocol):
    async def dispatch(self, envelope: Any, ctx: Any) -> bytes: ...

    async def on_start(self, ctx: Any) -> None: ...

    async def on_ready(self, ctx: Any) -> None: ...

    async def on_stop(self, ctx: Any) -> None: ...

    async def on_error(self, event: Any, ctx: Any) -> None: ...

    async def on_signaling_connecting(self, ctx: Any) -> None: ...

    async def on_signaling_connected(self, ctx: Any) -> None: ...

    async def on_signaling_disconnected(self, ctx: Any) -> None: ...

    async def on_websocket_connecting(self, event: Any, ctx: Any) -> None: ...

    async def on_websocket_connected(self, event: Any, ctx: Any) -> None: ...

    async def on_websocket_disconnected(self, event: Any, ctx: Any) -> None: ...

    async def on_webrtc_connecting(self, event: Any, ctx: Any) -> None: ...

    async def on_webrtc_connected(self, event: Any, ctx: Any) -> None: ...

    async def on_webrtc_disconnected(self, event: Any, ctx: Any) -> None: ...

    async def on_credential_renewed(self, event: Any, ctx: Any) -> None: ...

    async def on_credential_expiring(self, event: Any, ctx: Any) -> None: ...

    async def on_mailbox_backpressure(self, event: Any, ctx: Any) -> None: ...

    async def on_data_chunk(self, chunk: Any, sender: Any, ctx: Any) -> None: ...
