# Auto-generated by framework_codegen_python. DO NOT EDIT.
from __future__ import annotations

import sys
from typing import Dict

from google.protobuf.compiler import plugin_pb2 as plugin

from .generators import generate_local_workload_module


def main() -> int:
    """Main entry point for the protoc plugin."""
    data = sys.stdin.buffer.read()
    request = plugin.CodeGeneratorRequest()
    request.ParseFromString(data)

    parameters = parse_parameters(request.parameter)
    local_files = {file for file in parameters.get("LocalFiles", "").split(":") if file}

    # Build fully-qualified message name -> (package, proto file) map from the
    # full descriptor set so imported RPC message types resolve to their real
    # owner pb2 module instead of the current service's package.
    type_to_owner: dict[str, tuple[str, str]] = {}
    for file in request.proto_file:
        for message in file.message_type:
            full_name = f"{file.package}.{message.name}" if file.package else message.name
            type_to_owner[full_name] = (file.package, file.name)

    response = plugin.CodeGeneratorResponse()
    response.supported_features = plugin.CodeGeneratorResponse.FEATURE_PROTO3_OPTIONAL

    generated_any = False
    for file_name in request.file_to_generate:
        file_desc = next((file for file in request.proto_file if file.name == file_name), None)
        if file_desc is None:
            continue

        normalized_name = file_desc.name.replace("\\", "/")
        if local_files and normalized_name not in local_files:
            continue

        if not file_desc.service:
            continue

        try:
            generated = generate_local_workload_module(
                file_desc.package,
                normalized_name,
                file_desc.service,
                type_to_owner,
            )
        except NotImplementedError as error:
            response.error = str(error)
            sys.stdout.buffer.write(response.SerializeToString())
            return 0

        out = response.file.add()
        out.name = generated["name"]
        out.content = generated["content"]
        generated_any = True

    if not generated_any:
        response.error = (
            "Python workload codegen requires at least one local protobuf service. "
            "Client/proxy-only Python codegen is no longer supported."
        )
        sys.stdout.buffer.write(response.SerializeToString())
        return 0

    generated_dirs = set()
    for generated_file in response.file:
        if "/" not in generated_file.name:
            continue
        parts = generated_file.name.split("/")[:-1]
        current = ""
        for part in parts:
            current = f"{current}/{part}" if current else part
            generated_dirs.add(current)

    root_init = response.file.add()
    root_init.name = "__init__.py"
    root_init.content = ""

    for directory in sorted(generated_dirs):
        init_file = response.file.add()
        init_file.name = f"{directory}/__init__.py"
        init_file.content = ""

    sys.stdout.buffer.write(response.SerializeToString())
    return 0


def parse_parameters(param_str: str) -> Dict[str, str]:
    """Parse protoc plugin parameters in key=value format."""
    if not param_str:
        return {}

    params: Dict[str, str] = {}
    for pair in param_str.split(","):
        key, _, value = pair.partition("=")
        params[key] = value
    return params


if __name__ == "__main__":
    raise SystemExit(main())
