edition = 1
exports = []

[package]
name = "echo-real-client-app"
description = "Echo Client App"
authors = ["Actr Dev Team"]
license = "Apache-2.0"
tags = ["dev", "client"]

[package.actr_type]
manufacturer = "acme"
name = "echo-client-app"
version = "0.1.0"

[dependencies]
echo-server = { actr_type = "acme:EchoService:0.1.0" }

# Web platform specific configuration
[platform.web]
generate_types = true
types_output = "./src/generated/types"
generate_react_hooks = false
worker_type = "service-worker"
service_worker_path = "./public/actor.sw.js"
generate_sw_entry = true

[system.signaling]
url = "ws://localhost:8081/signaling/ws"

[system.deployment]
realm_id = 2368266035
ais_endpoint = "http://localhost:8081/ais"

[system.discovery]
visible = true

[system.observability]
filter_level = "info"
tracing_enabled = false

[system.webrtc]
force_relay = false
stun_urls = ["stun:localhost:3478"]
turn_urls = ["turn:localhost:3478"]

[acl]

[[acl.rules]]
permission = "allow"
# Allow server with actr_type = "acme:EchoService"
types = ["acme:EchoService:0.1.0"]
