edition = 1

[signaling]
url = "ws://localhost:8081/signaling/ws"

[ais_endpoint]
url = "http://localhost:8081/ais"

[deployment]
realm_id = 33554434
realm_secret = "rs_AclExampleSecret123456"

[discovery]
visible = true

[webrtc]
force_relay = false
stun_urls = ["stun:localhost:3478"]
turn_urls = ["turn:localhost:3478"]

# ACL configuration - allow greeter server

[acl]

[[acl.rules]]
permission = "allow"
type = "acme:greeter.GreeterService:1.0.0"

[scripts]
dev = "cargo run"
test = "cargo test"
