#!/bin/bash
# Test script for wasm-echo example — Full package verification flow
#
# Demonstrates the complete signing → verification → AIS registration flow:
#   1. Build guest actor to wasm32-unknown-unknown
#   2. Apply wasm-opt --asyncify transform
#   3. `actr pkg build` — pack WASM into a signed .actr package
#   4. Start actrix (signaling + AIS + MFR)
#   5. Seed MFR manufacturer + package records in DB
#   6. Server loads .actr package → verify signature → register with AIS → start
#   7. Client discovers WASM echo server, sends messages, verifies responses
#
# Usage:
#   ./start.sh              # Use default message "TestMsg"
#   ./start.sh "Hello"      # Send custom message

set -e
set -o pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🧪 Testing wasm-echo (Full Package Verification Flow)"
echo "    sign → verify → AIS register → WASM execute"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ── Paths ────────────────────────────────────────────────────────────────

WORKSPACE_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
echo "WORKSPACE_ROOT: "+"$WORKSPACE_ROOT"
# Actrium root is 3 levels up from WORKSPACE_ROOT (examples/rust):
#   examples/rust → actr/examples → actr → Actrium
ACTRIUM_DIR="$(cd "$WORKSPACE_ROOT/../../.." && pwd)"
ACTRIX_DIR="$ACTRIUM_DIR/actrix"
ACTR_REPO_DIR="$ACTRIUM_DIR/actr"
ACTR_CLI_MANIFEST="$ACTR_REPO_DIR/cli/Cargo.toml"
ACTRIX_CONFIG="$WORKSPACE_ROOT/actrix-config.toml"
PACKAGE_ECHO_DIR="$WORKSPACE_ROOT/package-echo"
SERVER_DIR="$PACKAGE_ECHO_DIR/server"
CLIENT_DIR="$PACKAGE_ECHO_DIR/client"
RELEASE_DIR="$PACKAGE_ECHO_DIR/release"

# MFR manufacturer name
MFR_NAME="acme"
# Key file will be generated by actr pkg keygen during Step 1
MFR_KEY_FILE=""
MFR_PUBKEY=""

# Ensure ~/.cargo/bin is in PATH
export PATH="$HOME/.cargo/bin:$PATH"

cd "$WORKSPACE_ROOT"

# Create logs directory
LOG_DIR="$WORKSPACE_ROOT/logs"
mkdir -p "$LOG_DIR"

# Ensure required helper scripts
source "$WORKSPACE_ROOT/scripts/ensure-tools.sh"
source "$WORKSPACE_ROOT/scripts/ensure-config-toml.sh"

# ── Clean stale database and config files ────────────────────────────────
# Remove DB files from previous runs so actrix starts with fresh keys.
# Without this, expired signing keys cause "Invalid credential format" errors.
echo ""
echo "🗑️  Cleaning stale database files..."
rm -rf "$WORKSPACE_ROOT/database"
# Also remove actr.toml files to ensure they are freshly copied from Actr.example.toml
rm -f "$SERVER_DIR/actr.toml" "$CLIENT_DIR/actr.toml"
echo -e "${GREEN}✅ Stale database cleaned${NC}"

# Ensure actr.toml files exist (will copy from Actr.example.toml)
echo ""
echo "🔍 Checking actr.toml files..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
ensure_actr_toml "$SERVER_DIR"
ensure_actr_toml "$CLIENT_DIR"
cp "$SERVER_DIR/Actr.example.toml" "$SERVER_DIR/actr.toml"
cp "$CLIENT_DIR/Actr.example.toml" "$CLIENT_DIR/actr.toml"
echo -e "${GREEN}✅ Synchronized actr.toml from Actr.example.toml${NC}"

# Ensure actrix-config.toml exists
ensure_actrix_config "$WORKSPACE_ROOT"

# ── Cleanup ──────────────────────────────────────────────────────────────

ACTRIX_PID=""
SERVER_PID=""
CLIENT_PID=""

cleanup() {
    echo ""
    echo "🧹 Cleaning up..."

    if [ -n "$ACTRIX_PID" ]; then
        echo "Stopping actrix (PID: $ACTRIX_PID)"
        kill $ACTRIX_PID 2>/dev/null || true
    fi

    if [ -n "$SERVER_PID" ]; then
        echo "Stopping package-echo-server (PID: $SERVER_PID)"
        kill $SERVER_PID 2>/dev/null || true
    fi

    if [ -n "$CLIENT_PID" ]; then
        echo "Stopping package-echo-client (PID: $CLIENT_PID)"
        kill $CLIENT_PID 2>/dev/null || true
    fi

    wait 2>/dev/null || true
    echo "✅ Cleanup complete"
}

trap cleanup EXIT INT TERM

# ── Step 0: Build WASM guest actor ───────────────────────────────────────

echo ""
echo -e "${BLUE}📦 Step 0: Building WASM guest actor (wasm32-unknown-unknown)...${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Use the package-echo guest directory (standalone WASM workspace)
GUEST_DIR="$PACKAGE_ECHO_DIR/guest"
BUILT_DIR="$RELEASE_DIR"
mkdir -p "$BUILT_DIR"

if [ ! -d "$GUEST_DIR" ]; then
    echo -e "${RED}❌ Guest directory not found: $GUEST_DIR${NC}"
    echo "The package-echo example reuses the wasm-echo guest actor."
    exit 1
fi

cargo build --manifest-path "$GUEST_DIR/Cargo.toml" \
    --target wasm32-unknown-unknown \
    --release 2>&1 | tail -5

WASM_RAW="$GUEST_DIR/target/wasm32-unknown-unknown/release/wasm_echo_guest.wasm"
if [ ! -f "$WASM_RAW" ]; then
    echo -e "${RED}❌ WASM build failed${NC}"
    exit 1
fi
echo -e "${GREEN}✅ WASM guest built: $(du -h "$WASM_RAW" | cut -f1) ${NC}"

# Apply wasm-opt --asyncify
echo ""
echo "🔧 Applying wasm-opt --asyncify transform..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

WASM_ASYNC="$BUILT_DIR/wasm_echo_guest.wasm"
if command -v wasm-opt > /dev/null 2>&1; then
    WASM_OPT_CMD="wasm-opt"
elif [ -f "$HOME/.cargo/bin/wasm-opt" ]; then
    WASM_OPT_CMD="$HOME/.cargo/bin/wasm-opt"
else
    echo -e "${YELLOW}⚠️  wasm-opt not found, installing via cargo...${NC}"
    cargo install wasm-opt 2>&1 | tail -3
    WASM_OPT_CMD="wasm-opt"
fi

echo "Using wasm-opt: $WASM_OPT_CMD"
$WASM_OPT_CMD --asyncify "$WASM_RAW" -o "$WASM_ASYNC" 2>&1

if [ ! -f "$WASM_ASYNC" ]; then
    echo -e "${RED}❌ wasm-opt failed${NC}"
    exit 1
fi
echo -e "${GREEN}✅ Asyncified WASM: $(du -h "$WASM_ASYNC" | cut -f1) ${NC}"

# ── Step 1: Build .actr package (sign with MFR key) ─────────────────────

echo ""
echo -e "${BLUE}📦 Step 1: Building signed .actr package...${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Ensure actr CLI is available
ACTR_CMD=""
if [ -x "$ACTRIUM_DIR/actr/target/debug/actr" ]; then
    ACTR_CMD="$ACTRIUM_DIR/actr/target/debug/actr"
elif [ -x "$ACTRIUM_DIR/actr/target/release/actr" ]; then
    ACTR_CMD="$ACTRIUM_DIR/actr/target/release/actr"
elif command -v actr > /dev/null 2>&1; then
    ACTR_CMD="actr"
else
    echo -e "${YELLOW}⚠️  actr CLI not found, building...${NC}"
    cd "$ACTRIUM_DIR/actr"
    cargo build --bin actr 2>&1 | tail -5
    ACTR_CMD="$ACTRIUM_DIR/actr/target/debug/actr"
    cd "$WORKSPACE_ROOT"
fi

echo "Using actr CLI: $ACTR_CMD"

# Generate a fresh MFR signing key pair using actr pkg keygen
MFR_KEY_FILE="$BUILT_DIR/dev-key.json"
$ACTR_CMD pkg keygen --output "$MFR_KEY_FILE" --force
MFR_PUBKEY=$(python3 -c "import json; print(json.load(open('$MFR_KEY_FILE'))['public_key'])")
echo "  Generated MFR key pair (pubkey: ${MFR_PUBKEY:0:20}...)"

# Write public-key.json for the server to load
PUBLIC_KEY_PATH="$RELEASE_DIR/public-key.json"
python3 -c "
import json
kc = json.load(open('$MFR_KEY_FILE'))
json.dump({'public_key': kc['public_key']}, open('$PUBLIC_KEY_PATH', 'w'), indent=2)
"
echo "  Public key written to: $PUBLIC_KEY_PATH"

ACTR_PACKAGE="$RELEASE_DIR/actrium-EchoService-0.1.0-wasm32-unknown-unknown.actr"

$ACTR_CMD pkg build \
    --binary "$WASM_ASYNC" \
    --config "$SERVER_DIR/actr.toml" \
    --key "$MFR_KEY_FILE" \
    --output "$ACTR_PACKAGE" \
    --target "wasm32-unknown-unknown"

if [ ! -f "$ACTR_PACKAGE" ]; then
    echo -e "${RED}❌ Package build failed${NC}"
    exit 1
fi

echo -e "${GREEN}✅ .actr package built: $(du -h "$ACTR_PACKAGE" | cut -f1)${NC}"

# ── Step 2: Ensure actrix is available ──────────────────────────────────

echo ""
echo -e "${BLUE}📦 Step 2: Checking actrix availability...${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

ACTRIX_CMD=""
if [ -x "$ACTRIX_DIR/target/debug/actrix" ]; then
    ACTRIX_CMD="$ACTRIX_DIR/target/debug/actrix"
    echo -e "${GREEN}✅ Actrix found: $ACTRIX_CMD${NC}"
elif [ -x "$ACTRIX_DIR/target/release/actrix" ]; then
    ACTRIX_CMD="$ACTRIX_DIR/target/release/actrix"
    echo -e "${GREEN}✅ Actrix found: $ACTRIX_CMD${NC}"
elif command -v actrix > /dev/null 2>&1; then
    ACTRIX_CMD="actrix"
    echo -e "${YELLOW}⚠️  Falling back to actrix from PATH: $(which actrix)${NC}"
else
    echo -e "${YELLOW}⚠️  Actrix not found in PATH or build directory. Attempting build...${NC}"
    if [ -d "$ACTRIX_DIR" ]; then
        cd "$ACTRIX_DIR"
        cargo build 2>&1 | tail -5
        if [ -x "$ACTRIX_DIR/target/debug/actrix" ]; then
            ACTRIX_CMD="$ACTRIX_DIR/target/debug/actrix"
        fi
        cd "$WORKSPACE_ROOT"
    fi

    if [ -z "$ACTRIX_CMD" ]; then
        echo -e "${RED}❌ Actrix not available. Install it first or build from $ACTRIX_DIR${NC}"
        exit 1
    fi
fi

# ── Step 3: Start actrix ────────────────────────────────────────────────

echo ""
echo -e "${BLUE}🚀 Step 3: Starting actrix (signaling + AIS + MFR)...${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

$ACTRIX_CMD --config "$ACTRIX_CONFIG" > "$LOG_DIR/actrix.log" 2>&1 &
ACTRIX_PID=$!

echo "Actrix started (PID: $ACTRIX_PID)"
echo "Waiting for actrix to be ready..."

MAX_WAIT=10
COUNTER=0
while [ $COUNTER -lt $MAX_WAIT ]; do
    if ! kill -0 $ACTRIX_PID 2>/dev/null; then
        echo -e "${RED}❌ Actrix failed to start${NC}"
        cat "$LOG_DIR/actrix.log"
        exit 1
    fi

    if lsof -i:8081 > /dev/null 2>&1 || nc -z localhost 8081 2>/dev/null; then
        echo -e "${GREEN}✅ Actrix is running and listening on port 8081${NC}"
        break
    fi

    sleep 1
    COUNTER=$((COUNTER + 1))
done

if [ $COUNTER -eq $MAX_WAIT ]; then
    echo -e "${RED}❌ Actrix not listening on port 8081 after ${MAX_WAIT} seconds${NC}"
    cat "$LOG_DIR/actrix.log"
    exit 1
fi

# ── Step 3.5: Seed realm + MFR data ────────────────────────────────────

echo ""
echo -e "${BLUE}🔑 Step 3.5: Seeding realm + MFR data in actrix DB...${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

sleep 2

# Extract realm IDs from actr.toml files
SERVER_REALM=$(grep -E 'realm_id\s*=' "$SERVER_DIR/actr.toml" | head -1 | sed 's/.*=\s*//' | tr -d ' ')
CLIENT_REALM=$(grep -E 'realm_id\s*=' "$CLIENT_DIR/actr.toml" | head -1 | sed 's/.*=\s*//' | tr -d ' ')

# Insert realms directly into SQLite (same approach as actrix fullstack tests)
ACTRIX_DB="$WORKSPACE_ROOT/database/actrix.db"

if [ ! -f "$ACTRIX_DB" ]; then
    echo -e "${RED}❌ Actrix database not found at $ACTRIX_DB${NC}"
    echo "Actrix may not have started properly."
    exit 1
fi

NOW=$(date +%s)

for REALM_ID in $SERVER_REALM $CLIENT_REALM; do
    echo "  Creating realm $REALM_ID..."
    sqlite3 "$ACTRIX_DB" \
        "INSERT OR IGNORE INTO realm (id, name, status, enabled, created_at, secret_current) VALUES ($REALM_ID, 'package-echo-realm', 'Active', 1, $NOW, '');"
done

echo -e "${GREEN}✅ Realms setup completed (realm IDs: $SERVER_REALM, $CLIENT_REALM)${NC}"

# Seed MFR manufacturer record with public key
echo "  Registering MFR manufacturer '$MFR_NAME' with public key..."
EXPIRES_AT=$((NOW + 86400 * 365))  # 1 year from now

# Compute key_id = "mfr-" + sha256(public_key_bytes)[..16hex]
# This MUST match the algorithm in actr_pack::compute_key_id and actrix-mfr::crypto::compute_key_id
MFR_KEY_ID=$(python3 -c "
import base64, hashlib
pub_bytes = base64.b64decode('$MFR_PUBKEY')
h = hashlib.sha256(pub_bytes).hexdigest()[:16]
print(f'mfr-{h}')
")
echo "  Computed key_id: $MFR_KEY_ID"

sqlite3 "$ACTRIX_DB" \
    "INSERT OR IGNORE INTO mfr (name, public_key, key_id, contact, status, created_at, verified_at, key_expires_at) VALUES ('$MFR_NAME', '$MFR_PUBKEY', '$MFR_KEY_ID', 'dev@example.com', 'active', $NOW, $NOW, $EXPIRES_AT);"

MFR_ID=$(sqlite3 "$ACTRIX_DB" "SELECT id FROM mfr WHERE name = '$MFR_NAME';")
echo -e "${GREEN}✅ MFR '$MFR_NAME' registered (id=$MFR_ID, key_id=$MFR_KEY_ID)${NC}"

# Client package: seed directly (no .actr package for client)
CLIENT_TYPE_STR="$MFR_NAME:package-echo-client-app:0.1.0"
sqlite3 "$ACTRIX_DB" \
    "INSERT OR IGNORE INTO mfr_package (mfr_id, manufacturer, name, version, type_str, target, manifest, signature, status, published_at) VALUES ($MFR_ID, '$MFR_NAME', 'package-echo-client-app', '0.1.0', '$CLIENT_TYPE_STR', 'native', '', '', 'active', $NOW);"

echo -e "${GREEN}✅ Client package record seeded${NC}"

# ── Step 4: Build host binaries ─────────────────────────────────────────

echo ""
echo -e "${BLUE}🔨 Step 4: Building host binaries...${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

if ! cargo build --bin package-echo-server --bin package-echo-client 2>&1; then
    echo -e "${RED}❌ Failed to build binaries${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Binaries built successfully${NC}"

# ── Step 4.5: Publish server .actr package via actr pkg publish ─────────

echo ""
echo -e "${BLUE}📡 Step 4.5: Publishing server .actr package via 'actr pkg publish'...${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

$ACTR_CMD pkg publish \
    --package "$ACTR_PACKAGE" \
    --keychain "$MFR_KEY_FILE" \
    --endpoint "http://localhost:8081" \
    --config "$SERVER_DIR/actr.toml"

if [ $? -ne 0 ]; then
    echo -e "${RED}❌ Package publish failed${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Server package published (with proto filing)${NC}"

# Debug: verify published data
echo "  [debug] mfr_package contents:"
sqlite3 "$ACTRIX_DB" "SELECT id, type_str, target, length(proto_files), status FROM mfr_package;"

# ── Step 5: Start WASM echo server (with package verification) ──────────

echo ""
echo -e "${BLUE}🚀 Step 5: Starting wasm-echo-server (loading .actr package)...${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

ACTR_PACKAGE_PATH="$ACTR_PACKAGE" \
TRUST_MODE="production" \
AIS_ENDPOINT="http://localhost:8081/ais" \
RUST_LOG="${RUST_LOG:-info}" \
cargo run --bin package-echo-server > "$LOG_DIR/package-echo-server.log" 2>&1 &
SERVER_PID=$!

echo "Server started (PID: $SERVER_PID)"
echo "Waiting for package-backed server to register..."

MAX_WAIT=20
COUNTER=0
while [ $COUNTER -lt $MAX_WAIT ]; do
    if ! kill -0 $SERVER_PID 2>/dev/null; then
        echo -e "${RED}❌ Package-backed server failed to start${NC}"
        cat "$LOG_DIR/package-echo-server.log"
        exit 1
    fi

    if grep -q "Echo Host fully started\|ActrNode started" "$LOG_DIR/package-echo-server.log" 2>/dev/null; then
        echo -e "${GREEN}✅ Package-backed server is running and registered${NC}"
        break
    fi

    sleep 1
    COUNTER=$((COUNTER + 1))
done

if [ $COUNTER -eq $MAX_WAIT ]; then
    echo -e "${YELLOW}⚠️  Server may not have fully registered, but continuing...${NC}"
fi

sleep 2

# ── Step 6: Run client with test input ──────────────────────────────────

echo ""
echo -e "${BLUE}🚀 Step 6: Running package-echo-client...${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

if [ -n "$1" ]; then
    TEST_INPUT="$1"
else
    TEST_INPUT="TestMsg"
fi

echo "Sending test message: \"$TEST_INPUT\""

(
    sleep 3
    echo "$TEST_INPUT"
    sleep 2
    echo "quit"
) | RUST_LOG="${RUST_LOG:-info}" cargo run --bin package-echo-client > "$LOG_DIR/package-echo-client.log" 2>&1 &
CLIENT_PID=$!

# Wait for client to finish (max 15 seconds)
COUNTER=0
while kill -0 $CLIENT_PID 2>/dev/null && [ $COUNTER -lt 15 ]; do
    sleep 1
    COUNTER=$((COUNTER + 1))
done

if kill -0 $CLIENT_PID 2>/dev/null; then
    echo -e "${YELLOW}⚠️  Client still running after 15 seconds, killing...${NC}"
    kill $CLIENT_PID 2>/dev/null || true
fi

# ── Step 7: Verify output ───────────────────────────────────────────────

echo ""
echo "🔍 Verifying output..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

if grep -q "\[Received reply\].*Echo: $TEST_INPUT" "$LOG_DIR/package-echo-client.log"; then
    echo -e "${GREEN}✅ Test PASSED: package-backed echo server response received${NC}"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "🎉 Full Package Verification Flow test completed!"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "✅ Validated end-to-end flow:"
    echo "   1. WASM guest compiled to wasm32-unknown-unknown"
    echo "   2. wasm-opt --asyncify transform applied"
    echo "   3. actr pkg build → signed .actr package (MFR key: $MFR_NAME)"
    echo "   4. Server loaded .actr → verified MFR signature"
    echo "   5. Server registered with AIS (manifest_raw + mfr_signature)"
    echo "   6. AIS verified MFR identity → issued credential"
    echo "   7. ActrNode started with verified credential"
    echo "   8. Client discovered server → echo message confirmed"
    echo ""
    echo "Client output:"
    cat "$LOG_DIR/package-echo-client.log" | grep "Received reply" || true
    echo ""
    echo "📖 View full logs:"
    echo "   cat $LOG_DIR/package-echo-client.log  # Client logs"
    echo "   cat $LOG_DIR/package-echo-server.log  # Server logs"
    echo "   tail -f $LOG_DIR/actrix.log        # Actrix logs"
    echo ""
    exit 0
else
    echo -e "${RED}❌ Test FAILED: Expected package-backed echo server response not found${NC}"
    echo -e "${RED}   Looking for: [Received reply] Echo: $TEST_INPUT${NC}"
    echo ""
    echo "Client output:"
    cat "$LOG_DIR/package-echo-client.log"
    echo ""
    echo "Server output (last 30 lines):"
    tail -30 "$LOG_DIR/package-echo-server.log"
    echo ""
    echo "Actrix output (last 30 lines):"
    tail -30 "$LOG_DIR/actrix.log"
    exit 1
fi
