//! WASM actor end-to-end test fixture
//!
//! Verification target: a real wasm32 actor that implements the `Context` trait
//! via `actr-framework` guest module, calls `ctx.call_raw()` inside the handler to trigger
//! asyncify suspend/resume, and returns the host's response as its own response.
//!
//! # Test protocol
//!
//! - request: raw bytes containing a 4-byte little-endian i32 value `x`
//! - actor calls `ctx.call_raw(self_id, "test/double", payload_bytes)`
//! - host mock returns `x * 2` (4-byte little-endian i32)
//! - actor response: bytes returned by host (i.e. `x * 2`)
//!
//! # Expected
//!
//! host calls `actr_handle(request=5_i32_le)` and eventually gets response `10_i32_le`

use actr_framework::{Context, MessageDispatcher, Workload, entry};
use actr_protocol::{ActorResult, ActrError, RpcEnvelope};
use async_trait::async_trait;
use bytes::Bytes;

// ── Workload ──────────────────────────────────────────────────────────────────

#[derive(Default)]
pub struct DoubleActor;

pub struct DoubleDispatcher;

#[async_trait]
impl MessageDispatcher for DoubleDispatcher {
    type Workload = DoubleActor;

    async fn dispatch<C: Context>(
        _workload: &Self::Workload,
        envelope: RpcEnvelope,
        ctx: &C,
    ) -> ActorResult<Bytes> {
        match envelope.route_key.as_str() {
            "test/double" => {
                // payload: 4-byte little-endian i32 (RpcEnvelope.payload is optional)
                let payload = envelope.payload.unwrap_or_default();
                if payload.len() < 4 {
                    return Err(ActrError::InvalidArgument("payload too short".into()));
                }
                let x = i32::from_le_bytes([payload[0], payload[1], payload[2], payload[3]]);

                // Call ctx.call_raw() -> triggers asyncify!
                let target = ctx.self_id().clone();
                let resp = ctx
                    .call_raw(&target, "test/double_impl", Bytes::from(x.to_le_bytes().to_vec()))
                    .await?;

                Ok(resp)
            }
            _ => Err(ActrError::UnknownRoute(envelope.route_key)),
        }
    }
}

impl Workload for DoubleActor {
    type Dispatcher = DoubleDispatcher;
}

// ── ABI exports (generated by entry! macro) ──────────────────────────────────

entry!(DoubleActor);
