edition = 1
exports = []

[package]
name = "echo-real-client-app"
manufacturer = "acme"
type = "echo-client-app"
description = "Echo Client App demonstrating ActrConnect"
authors = []

[dependencies]

[system.signaling]
url = "ws://localhost:8081/signaling/ws"

[system.deployment]
realm = 0

[system.discovery]
visible = true

[scripts]
dev = "cargo run"
test = "cargo test"
