edition = 1
exports = []

[package]
name = "file-transfer-receiver"
manufacturer = "acme"
type = "file_transfer.FileTransferService"
description = "File transfer receiver using DataStream API"
authors = []

[dependencies]

[system.signaling]
url = "ws://127.0.0.1:8081/"

[system.deployment]
realm = 1001

[system.discovery]
visible = true

[scripts]
dev = "cargo run"
test = "cargo test"
