// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/wit-compile-web — do not edit.
//
// Source: core/framework/wit/actr-workload.wit
// Regenerate with: cargo run -p actr-wit-compile-web
// Drift check:      cargo run -p actr-wit-compile-web -- --check

//! Guest-side wrappers around `interface host` imports.
//!
//! Each WIT host function appears here twice: once as a raw
//! `#[wasm_bindgen] extern "C"` declaration that resolves
//! against the JS `actrHost*` namespace the DOM bridge
//! exposes, and once as a typed Rust `async fn` that handles
//! serde marshaling and promise awaiting.
//!
//! Every wrapper is `async` — even for imports that look
//! sync in WIT — because the JS host is free to implement
//! any of them as a Promise-returning function, and making
//! callers uniformly write `.await` keeps the surface
//! predictable.
#![allow(clippy::useless_conversion)]
#![allow(clippy::unused_unit)]

use wasm_bindgen::prelude::*;
use wasm_bindgen_futures::JsFuture;

use crate::types::*;

/// Convert a serde-wasm-bindgen marshaling error into a `JsValue`
/// so wrapper signatures stay uniform.
#[inline]
fn serde_err(e: serde_wasm_bindgen::Error) -> JsValue {
    JsValue::from(e)
}

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(catch, js_name = "actrHostCall")]
    fn __actr_host_call(target: JsValue, route_key: JsValue, payload: JsValue) -> Result<js_sys::Promise, JsValue>;
    #[wasm_bindgen(catch, js_name = "actrHostCallRaw")]
    fn __actr_host_call_raw(target: JsValue, route_key: JsValue, payload: JsValue) -> Result<js_sys::Promise, JsValue>;
    #[wasm_bindgen(catch, js_name = "actrHostDiscover")]
    fn __actr_host_discover(target_type: JsValue) -> Result<js_sys::Promise, JsValue>;
    #[wasm_bindgen(catch, js_name = "actrHostGetCallerId")]
    fn __actr_host_get_caller_id() -> Result<js_sys::Promise, JsValue>;
    #[wasm_bindgen(catch, js_name = "actrHostGetRequestId")]
    fn __actr_host_get_request_id() -> Result<js_sys::Promise, JsValue>;
    #[wasm_bindgen(catch, js_name = "actrHostGetSelfId")]
    fn __actr_host_get_self_id() -> Result<js_sys::Promise, JsValue>;
    #[wasm_bindgen(catch, js_name = "actrHostLogMessage")]
    fn __actr_host_log_message(level: JsValue, message: JsValue) -> Result<js_sys::Promise, JsValue>;
    #[wasm_bindgen(catch, js_name = "actrHostTell")]
    fn __actr_host_tell(target: JsValue, route_key: JsValue, payload: JsValue) -> Result<js_sys::Promise, JsValue>;
}

/// Guest-side wrapper for WIT `host.call`.
pub async fn call(target: Dest, route_key: String, payload: Vec<u8>) -> Result<Result<Vec<u8>, ActrError>, JsValue> {
    let __js_arg0 = serde_wasm_bindgen::to_value(&target).map_err(serde_err)?;
    let __js_arg1 = serde_wasm_bindgen::to_value(&route_key).map_err(serde_err)?;
    let __js_arg2 = serde_wasm_bindgen::to_value(&payload).map_err(serde_err)?;
    let __js_promise = __actr_host_call(__js_arg0, __js_arg1, __js_arg2)?;
    let __js_result = JsFuture::from(__js_promise).await?;
    let __out = serde_wasm_bindgen::from_value(__js_result).map_err(serde_err)?;
    Ok(__out)
}

/// Guest-side wrapper for WIT `host.call-raw`.
pub async fn call_raw(target: ActrId, route_key: String, payload: Vec<u8>) -> Result<Result<Vec<u8>, ActrError>, JsValue> {
    let __js_arg0 = serde_wasm_bindgen::to_value(&target).map_err(serde_err)?;
    let __js_arg1 = serde_wasm_bindgen::to_value(&route_key).map_err(serde_err)?;
    let __js_arg2 = serde_wasm_bindgen::to_value(&payload).map_err(serde_err)?;
    let __js_promise = __actr_host_call_raw(__js_arg0, __js_arg1, __js_arg2)?;
    let __js_result = JsFuture::from(__js_promise).await?;
    let __out = serde_wasm_bindgen::from_value(__js_result).map_err(serde_err)?;
    Ok(__out)
}

/// Guest-side wrapper for WIT `host.discover`.
pub async fn discover(target_type: ActrType) -> Result<Result<ActrId, ActrError>, JsValue> {
    let __js_arg0 = serde_wasm_bindgen::to_value(&target_type).map_err(serde_err)?;
    let __js_promise = __actr_host_discover(__js_arg0)?;
    let __js_result = JsFuture::from(__js_promise).await?;
    let __out = serde_wasm_bindgen::from_value(__js_result).map_err(serde_err)?;
    Ok(__out)
}

/// Guest-side wrapper for WIT `host.get-caller-id`.
pub async fn get_caller_id() -> Result<Option<ActrId>, JsValue> {
    let __js_promise = __actr_host_get_caller_id()?;
    let __js_result = JsFuture::from(__js_promise).await?;
    let __out = serde_wasm_bindgen::from_value(__js_result).map_err(serde_err)?;
    Ok(__out)
}

/// Guest-side wrapper for WIT `host.get-request-id`.
pub async fn get_request_id() -> Result<String, JsValue> {
    let __js_promise = __actr_host_get_request_id()?;
    let __js_result = JsFuture::from(__js_promise).await?;
    let __out = serde_wasm_bindgen::from_value(__js_result).map_err(serde_err)?;
    Ok(__out)
}

/// Guest-side wrapper for WIT `host.get-self-id`.
pub async fn get_self_id() -> Result<ActrId, JsValue> {
    let __js_promise = __actr_host_get_self_id()?;
    let __js_result = JsFuture::from(__js_promise).await?;
    let __out = serde_wasm_bindgen::from_value(__js_result).map_err(serde_err)?;
    Ok(__out)
}

/// Guest-side wrapper for WIT `host.log-message`.
pub async fn log_message(level: String, message: String) -> Result<(), JsValue> {
    let __js_arg0 = serde_wasm_bindgen::to_value(&level).map_err(serde_err)?;
    let __js_arg1 = serde_wasm_bindgen::to_value(&message).map_err(serde_err)?;
    let __js_promise = __actr_host_log_message(__js_arg0, __js_arg1)?;
    let __js_result = JsFuture::from(__js_promise).await?;
    let _ = __js_result;
    Ok(())
}

/// Guest-side wrapper for WIT `host.tell`.
pub async fn tell(target: Dest, route_key: String, payload: Vec<u8>) -> Result<Result<(), ActrError>, JsValue> {
    let __js_arg0 = serde_wasm_bindgen::to_value(&target).map_err(serde_err)?;
    let __js_arg1 = serde_wasm_bindgen::to_value(&route_key).map_err(serde_err)?;
    let __js_arg2 = serde_wasm_bindgen::to_value(&payload).map_err(serde_err)?;
    let __js_promise = __actr_host_tell(__js_arg0, __js_arg1, __js_arg2)?;
    let __js_result = JsFuture::from(__js_promise).await?;
    let __out = serde_wasm_bindgen::from_value(__js_result).map_err(serde_err)?;
    Ok(__out)
}

