// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by tools/wit-compile-web — do not edit.
//
// Source: core/framework/wit/actr-workload.wit
// Regenerate with: cargo run -p actr-wit-compile-web
// Drift check:      cargo run -p actr-wit-compile-web -- --check

//! Host-side wrappers around `interface workload` exports.
//!
//! Emits the `Workload` trait the user implements and a set
//! of `#[wasm_bindgen]` free functions the browser host
//! (service worker / DOM bridge) calls. Each entry point
//! deserialises JS arguments, dispatches to the registered
//! `Workload` instance, and serialises the response back.
//!
//! Registration is single-shot via `set_workload` — the wasm
//! bootstrap installs one boxed handler, and every export
//! call resolves against it. Attempting to dispatch before
//! registration traps with an explicit JsError.
#![allow(clippy::unused_unit)]

use std::cell::RefCell;

use async_trait::async_trait;
use wasm_bindgen::prelude::*;

use crate::types::*;

/// User-implemented workload trait. One instance per wasm
/// module; install with `set_workload`.
///
/// Method shapes mirror the WIT `workload` interface exactly,
/// including which hooks are fallible (the four lifecycle
/// hooks return `Result<_, ActrError>`) and which are
/// infallible (all the observation hooks).
#[async_trait(?Send)]
pub trait Workload: 'static {
    async fn dispatch(&self, envelope: RpcEnvelope) -> Result<Vec<u8>, ActrError>;
    async fn on_credential_expiring(&self, event: CredentialEvent);
    async fn on_credential_renewed(&self, event: CredentialEvent);
    async fn on_error(&self, event: ErrorEvent) -> Result<(), ActrError>;
    async fn on_mailbox_backpressure(&self, event: BackpressureEvent);
    async fn on_ready(&self) -> Result<(), ActrError>;
    async fn on_signaling_connected(&self);
    async fn on_signaling_connecting(&self);
    async fn on_signaling_disconnected(&self);
    async fn on_start(&self) -> Result<(), ActrError>;
    async fn on_stop(&self) -> Result<(), ActrError>;
    async fn on_webrtc_connected(&self, event: PeerEvent);
    async fn on_webrtc_connecting(&self, event: PeerEvent);
    async fn on_webrtc_disconnected(&self, event: PeerEvent);
    async fn on_websocket_connected(&self, event: PeerEvent);
    async fn on_websocket_connecting(&self, event: PeerEvent);
    async fn on_websocket_disconnected(&self, event: PeerEvent);
}

thread_local! {
    static WORKLOAD: RefCell<Option<&'static dyn Workload>> = const { RefCell::new(None) };
}

/// Install the single workload implementation. Returns an error if
/// called more than once — the second caller's `Box` is discarded so
/// the first registration stays authoritative.
///
/// The installed handler is intentionally leaked to `'static`: the
/// browser path registers exactly one workload during bootstrap and
/// keeps it alive for the lifetime of the wasm instance.
pub fn set_workload<W: Workload>(w: W) -> Result<(), &'static str> {
    WORKLOAD.with(|slot| {
        let mut slot = slot.borrow_mut();
        if slot.is_some() {
            return Err("actr-web-abi: workload already registered");
        }
        let leaked: &'static dyn Workload = Box::leak(Box::new(w));
        *slot = Some(leaked);
        Ok(())
    })
}

#[inline]
fn workload() -> Result<&'static dyn Workload, JsValue> {
    WORKLOAD
        .with(|slot| slot.borrow().as_ref().copied())
        .ok_or_else(|| JsValue::from_str("actr-web-abi: workload not registered"))
}

#[inline]
fn serde_err(e: serde_wasm_bindgen::Error) -> JsValue {
    JsValue::from(e)
}

/// Host-exported entry for WIT `workload.dispatch`.
#[wasm_bindgen(js_name = "dispatch")]
pub async fn __actr_workload_dispatch(envelope: JsValue) -> Result<JsValue, JsValue> {
    let __w = workload()?;
    let __p_envelope: RpcEnvelope = serde_wasm_bindgen::from_value(envelope).map_err(serde_err)?;
    let __r = __w.dispatch(__p_envelope).await;
    serde_wasm_bindgen::to_value(&__r).map_err(serde_err)
}

/// Host-exported entry for WIT `workload.on-credential-expiring`.
#[wasm_bindgen(js_name = "on_credential_expiring")]
pub async fn __actr_workload_on_credential_expiring(event: JsValue) -> Result<JsValue, JsValue> {
    let __w = workload()?;
    let __p_event: CredentialEvent = serde_wasm_bindgen::from_value(event).map_err(serde_err)?;
    __w.on_credential_expiring(__p_event).await;
    Ok(JsValue::UNDEFINED)
}

/// Host-exported entry for WIT `workload.on-credential-renewed`.
#[wasm_bindgen(js_name = "on_credential_renewed")]
pub async fn __actr_workload_on_credential_renewed(event: JsValue) -> Result<JsValue, JsValue> {
    let __w = workload()?;
    let __p_event: CredentialEvent = serde_wasm_bindgen::from_value(event).map_err(serde_err)?;
    __w.on_credential_renewed(__p_event).await;
    Ok(JsValue::UNDEFINED)
}

/// Host-exported entry for WIT `workload.on-error`.
#[wasm_bindgen(js_name = "on_error")]
pub async fn __actr_workload_on_error(event: JsValue) -> Result<JsValue, JsValue> {
    let __w = workload()?;
    let __p_event: ErrorEvent = serde_wasm_bindgen::from_value(event).map_err(serde_err)?;
    let __r = __w.on_error(__p_event).await;
    serde_wasm_bindgen::to_value(&__r).map_err(serde_err)
}

/// Host-exported entry for WIT `workload.on-mailbox-backpressure`.
#[wasm_bindgen(js_name = "on_mailbox_backpressure")]
pub async fn __actr_workload_on_mailbox_backpressure(event: JsValue) -> Result<JsValue, JsValue> {
    let __w = workload()?;
    let __p_event: BackpressureEvent = serde_wasm_bindgen::from_value(event).map_err(serde_err)?;
    __w.on_mailbox_backpressure(__p_event).await;
    Ok(JsValue::UNDEFINED)
}

/// Host-exported entry for WIT `workload.on-ready`.
#[wasm_bindgen(js_name = "on_ready")]
pub async fn __actr_workload_on_ready() -> Result<JsValue, JsValue> {
    let __w = workload()?;
    let __r = __w.on_ready().await;
    serde_wasm_bindgen::to_value(&__r).map_err(serde_err)
}

/// Host-exported entry for WIT `workload.on-signaling-connected`.
#[wasm_bindgen(js_name = "on_signaling_connected")]
pub async fn __actr_workload_on_signaling_connected() -> Result<JsValue, JsValue> {
    let __w = workload()?;
    __w.on_signaling_connected().await;
    Ok(JsValue::UNDEFINED)
}

/// Host-exported entry for WIT `workload.on-signaling-connecting`.
#[wasm_bindgen(js_name = "on_signaling_connecting")]
pub async fn __actr_workload_on_signaling_connecting() -> Result<JsValue, JsValue> {
    let __w = workload()?;
    __w.on_signaling_connecting().await;
    Ok(JsValue::UNDEFINED)
}

/// Host-exported entry for WIT `workload.on-signaling-disconnected`.
#[wasm_bindgen(js_name = "on_signaling_disconnected")]
pub async fn __actr_workload_on_signaling_disconnected() -> Result<JsValue, JsValue> {
    let __w = workload()?;
    __w.on_signaling_disconnected().await;
    Ok(JsValue::UNDEFINED)
}

/// Host-exported entry for WIT `workload.on-start`.
#[wasm_bindgen(js_name = "on_start")]
pub async fn __actr_workload_on_start() -> Result<JsValue, JsValue> {
    let __w = workload()?;
    let __r = __w.on_start().await;
    serde_wasm_bindgen::to_value(&__r).map_err(serde_err)
}

/// Host-exported entry for WIT `workload.on-stop`.
#[wasm_bindgen(js_name = "on_stop")]
pub async fn __actr_workload_on_stop() -> Result<JsValue, JsValue> {
    let __w = workload()?;
    let __r = __w.on_stop().await;
    serde_wasm_bindgen::to_value(&__r).map_err(serde_err)
}

/// Host-exported entry for WIT `workload.on-webrtc-connected`.
#[wasm_bindgen(js_name = "on_webrtc_connected")]
pub async fn __actr_workload_on_webrtc_connected(event: JsValue) -> Result<JsValue, JsValue> {
    let __w = workload()?;
    let __p_event: PeerEvent = serde_wasm_bindgen::from_value(event).map_err(serde_err)?;
    __w.on_webrtc_connected(__p_event).await;
    Ok(JsValue::UNDEFINED)
}

/// Host-exported entry for WIT `workload.on-webrtc-connecting`.
#[wasm_bindgen(js_name = "on_webrtc_connecting")]
pub async fn __actr_workload_on_webrtc_connecting(event: JsValue) -> Result<JsValue, JsValue> {
    let __w = workload()?;
    let __p_event: PeerEvent = serde_wasm_bindgen::from_value(event).map_err(serde_err)?;
    __w.on_webrtc_connecting(__p_event).await;
    Ok(JsValue::UNDEFINED)
}

/// Host-exported entry for WIT `workload.on-webrtc-disconnected`.
#[wasm_bindgen(js_name = "on_webrtc_disconnected")]
pub async fn __actr_workload_on_webrtc_disconnected(event: JsValue) -> Result<JsValue, JsValue> {
    let __w = workload()?;
    let __p_event: PeerEvent = serde_wasm_bindgen::from_value(event).map_err(serde_err)?;
    __w.on_webrtc_disconnected(__p_event).await;
    Ok(JsValue::UNDEFINED)
}

/// Host-exported entry for WIT `workload.on-websocket-connected`.
#[wasm_bindgen(js_name = "on_websocket_connected")]
pub async fn __actr_workload_on_websocket_connected(event: JsValue) -> Result<JsValue, JsValue> {
    let __w = workload()?;
    let __p_event: PeerEvent = serde_wasm_bindgen::from_value(event).map_err(serde_err)?;
    __w.on_websocket_connected(__p_event).await;
    Ok(JsValue::UNDEFINED)
}

/// Host-exported entry for WIT `workload.on-websocket-connecting`.
#[wasm_bindgen(js_name = "on_websocket_connecting")]
pub async fn __actr_workload_on_websocket_connecting(event: JsValue) -> Result<JsValue, JsValue> {
    let __w = workload()?;
    let __p_event: PeerEvent = serde_wasm_bindgen::from_value(event).map_err(serde_err)?;
    __w.on_websocket_connecting(__p_event).await;
    Ok(JsValue::UNDEFINED)
}

/// Host-exported entry for WIT `workload.on-websocket-disconnected`.
#[wasm_bindgen(js_name = "on_websocket_disconnected")]
pub async fn __actr_workload_on_websocket_disconnected(event: JsValue) -> Result<JsValue, JsValue> {
    let __w = workload()?;
    let __p_event: PeerEvent = serde_wasm_bindgen::from_value(event).map_err(serde_err)?;
    __w.on_websocket_disconnected(__p_event).await;
    Ok(JsValue::UNDEFINED)
}

