//! Asyncify protocol POC verification
//!
//! Verification goal: a WASM module calling a host import, after wasm-opt --asyncify transform,
//! the host can suspend WASM at the host import call site, perform async IO, then resume WASM.
//!
//! Protocol sequence:
//! 1. Host calls `compute(x)` (WASM export)
//! 2. WASM calls `host_get_value(x)` (host import)
//! 3. Inside host import: call `asyncify_start_unwind(data_ptr)` -> return dummy value
//! 4. WASM asyncify code detects unwind state -> saves all locals to data buffer -> returns
//! 5. Host calls `asyncify_stop_unwind()`
//! 6. Host performs "async IO" (mock here: returns x * 2)
//! 7. Host calls `asyncify_start_rewind(data_ptr)`
//! 8. Host re-calls `compute(x)`
//! 9. WASM asyncify code detects rewind state -> restores state from buffer -> re-calls `host_get_value`
//! 10. Inside host import: call `asyncify_stop_rewind()` -> return real IO result
//! 11. WASM continues normal execution, completes `x + from_host`, returns result

#![cfg(feature = "wasm-engine")]

// asyncify-transformed WASM fixture bytes (generated by build.sh)
include!("asyncify_fixture.rs");

use wasmtime::{Caller, Engine, Instance, Linker, Module, Store};

// ─── asyncify protocol state ───────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq, Default)]
enum AsyncifyMode {
    #[default]
    Normal,
    Unwinding,
    Rewinding,
}

#[derive(Debug, Default)]
struct HostData {
    mode: AsyncifyMode,
    /// asyncify data buffer start address in WASM linear memory
    data_ptr: i32,
    /// Input received by host import (saved during unwind, used to trigger IO)
    pending_input: Option<i32>,
    /// Result after "async IO" completes (returned to WASM during rewind)
    rewind_result: Option<i32>,
}

// ─── asyncify data buffer layout ────────────────────────────────────────────────
//
// asyncify_start_unwind(ptr) expects WASM linear memory at ptr:
//   [ptr+0] i32 = asyncify stack current write position (initial = ptr + 8)
//   [ptr+4] i32 = asyncify stack end position
//
// We reserve 4KB at the end of WASM page 0 for the asyncify stack:

const ASYNCIFY_DATA_PTR: i32 = 0x8000; // 32KB offset (within WASM page 0)
const ASYNCIFY_STACK_START: i32 = ASYNCIFY_DATA_PTR + 8;
const ASYNCIFY_STACK_END: i32 = ASYNCIFY_DATA_PTR + 0x1000; // +4KB

// ─── Helper: initialize asyncify data buffer in WASM linear memory ────────────────────

fn init_asyncify_data(instance: &Instance, store: &mut Store<HostData>) {
    let memory = instance
        .get_memory(&mut *store, "memory")
        .expect("no memory export");
    let data = memory.data_mut(&mut *store);
    let base = ASYNCIFY_DATA_PTR as usize;
    // [ptr+0]: current stack write position = ASYNCIFY_STACK_START
    data[base..base + 4].copy_from_slice(&ASYNCIFY_STACK_START.to_le_bytes());
    // [ptr+4]: stack end position = ASYNCIFY_STACK_END
    data[base + 4..base + 8].copy_from_slice(&ASYNCIFY_STACK_END.to_le_bytes());

    store.data_mut().data_ptr = ASYNCIFY_DATA_PTR;
}

// ─── asyncify drive loop ────────────────────────────────────────────────────────

fn drive(instance: &Instance, store: &mut Store<HostData>, x: i32) -> i32 {
    let compute = instance
        .get_typed_func::<i32, i32>(&mut *store, "compute")
        .expect("no compute export");
    let stop_unwind = instance
        .get_typed_func::<(), ()>(&mut *store, "asyncify_stop_unwind")
        .expect("no asyncify_stop_unwind");
    let start_rewind = instance
        .get_typed_func::<i32, ()>(&mut *store, "asyncify_start_rewind")
        .expect("no asyncify_start_rewind");

    loop {
        let result = compute.call(&mut *store, x).expect("compute call failed");

        match store.data().mode {
            AsyncifyMode::Unwinding => {
                // WASM has unwound and saved state, stop unwind
                stop_unwind
                    .call(&mut *store, ())
                    .expect("stop_unwind failed");

                // Simulate "async IO": return x * 2
                let input = store.data().pending_input.unwrap();
                let io_result = input * 2;
                tracing::debug!(input, io_result, "mock IO done");

                // Prepare rewind
                store.data_mut().rewind_result = Some(io_result);
                store.data_mut().mode = AsyncifyMode::Rewinding;

                let data_ptr = store.data().data_ptr;
                start_rewind
                    .call(&mut *store, data_ptr)
                    .expect("start_rewind failed");
                // Note: do NOT reset the data buffer! Unwind already wrote state into it;
                // rewind needs to read and restore from the buffer -- resetting would destroy saved state.
                // Continue loop, re-call compute to trigger rewind
            }
            AsyncifyMode::Normal => {
                // Normal completion (including post-rewind normal finish)
                return result;
            }
            AsyncifyMode::Rewinding => {
                // After rewind completes, host import sets mode back to Normal;
                // should not reach here
                unreachable!("drive loop: unexpected Rewinding state after compute returned");
            }
        }
    }
}

// ─── Test cases ─────────────────────────────────────────────────────────────────

#[test]
fn asyncify_suspend_resume_basic() {
    let engine = Engine::default();
    let module = Module::new(&engine, ASYNCIFY_FIXTURE_WASM).expect("module load failed");

    let mut linker = Linker::<HostData>::new(&engine);

    // Register host import: host_get_value(x) -> i32
    // Triggers unwind in Normal mode, returns real result in Rewinding mode
    linker
        .func_wrap(
            "env",
            "host_get_value",
            |mut caller: Caller<HostData>, x: i32| -> i32 {
                let mode = caller.data().mode.clone();
                match mode {
                    AsyncifyMode::Rewinding => {
                        // Rewind phase: return previously computed IO result, stop rewind
                        let result = caller.data_mut().rewind_result.take().unwrap();
                        caller.data_mut().mode = AsyncifyMode::Normal;

                        // Call asyncify_stop_rewind()
                        let stop_rewind = caller
                            .get_export("asyncify_stop_rewind")
                            .and_then(|e| e.into_func())
                            .expect("no asyncify_stop_rewind");
                        stop_rewind
                            .typed::<(), ()>(&caller)
                            .unwrap()
                            .call(&mut caller, ())
                            .expect("stop_rewind failed");

                        tracing::debug!(result, "host_get_value rewind -> returning real result");
                        result
                    }
                    AsyncifyMode::Normal => {
                        // First call: trigger unwind, suspend WASM
                        caller.data_mut().pending_input = Some(x);
                        caller.data_mut().mode = AsyncifyMode::Unwinding;

                        let data_ptr = caller.data().data_ptr;

                        // Call asyncify_start_unwind(data_ptr)
                        let start_unwind = caller
                            .get_export("asyncify_start_unwind")
                            .and_then(|e| e.into_func())
                            .expect("no asyncify_start_unwind");
                        start_unwind
                            .typed::<i32, ()>(&caller)
                            .unwrap()
                            .call(&mut caller, data_ptr)
                            .expect("start_unwind failed");

                        tracing::debug!(x, "host_get_value triggered unwind, suspending WASM");
                        0 // dummy, ignored during unwind
                    }
                    AsyncifyMode::Unwinding => {
                        // Should not call host import again during unwind
                        unreachable!("host_get_value called while unwinding")
                    }
                }
            },
        )
        .expect("linker func_wrap failed");

    let mut store = Store::new(&engine, HostData::default());
    let instance = linker
        .instantiate(&mut store, &module)
        .expect("instantiate failed");

    init_asyncify_data(&instance, &mut store);

    // compute(5): WASM calls host_get_value(5), host mock returns 10 (5*2)
    // Expected: 5 + 10 = 15
    let result = drive(&instance, &mut store, 5);
    assert_eq!(result, 15, "asyncify suspend/resume result should be 15");

    tracing::info!(result, "asyncify POC verified");
}

#[test]
fn asyncify_multiple_calls() {
    let engine = Engine::default();
    let module = Module::new(&engine, ASYNCIFY_FIXTURE_WASM).expect("module load failed");

    let mut linker = Linker::<HostData>::new(&engine);
    linker
        .func_wrap(
            "env",
            "host_get_value",
            |mut caller: Caller<HostData>, x: i32| -> i32 {
                let mode = caller.data().mode.clone();
                match mode {
                    AsyncifyMode::Rewinding => {
                        let result = caller.data_mut().rewind_result.take().unwrap();
                        caller.data_mut().mode = AsyncifyMode::Normal;
                        let stop_rewind = caller
                            .get_export("asyncify_stop_rewind")
                            .and_then(|e| e.into_func())
                            .unwrap();
                        stop_rewind
                            .typed::<(), ()>(&caller)
                            .unwrap()
                            .call(&mut caller, ())
                            .unwrap();
                        result
                    }
                    AsyncifyMode::Normal => {
                        caller.data_mut().pending_input = Some(x);
                        caller.data_mut().mode = AsyncifyMode::Unwinding;
                        let data_ptr = caller.data().data_ptr;
                        let start_unwind = caller
                            .get_export("asyncify_start_unwind")
                            .and_then(|e| e.into_func())
                            .unwrap();
                        start_unwind
                            .typed::<i32, ()>(&caller)
                            .unwrap()
                            .call(&mut caller, data_ptr)
                            .unwrap();
                        0
                    }
                    AsyncifyMode::Unwinding => unreachable!(),
                }
            },
        )
        .unwrap();

    // Multiple calls, each with an independent instance (asyncify data buffer reset)
    for x in [1i32, 7, 42, 100] {
        let mut store = Store::new(&engine, HostData::default());
        let instance = linker.instantiate(&mut store, &module).unwrap();
        init_asyncify_data(&instance, &mut store);

        let result = drive(&instance, &mut store, x);
        assert_eq!(
            result,
            x + x * 2,
            "compute({x}) should return {}",
            x + x * 2
        );
    }

    tracing::info!("asyncify multiple calls verified");
}
