#!/bin/bash
set -e

echo "🔨 Building Echo Server WASM..."
echo "   User workload + SW runtime -> single WASM"

# Ensure a writable temp directory for wasm-bindgen install.
TMPDIR="${TMPDIR:-$(pwd)/.tmp}"
export TMPDIR
mkdir -p "$TMPDIR"

# Output directory (written to server/public)
OUT_DIR="../public"

# Remove previous build output
rm -f "$OUT_DIR"/echo_server*.wasm "$OUT_DIR"/echo_server*.js "$OUT_DIR"/echo_server*.d.ts

# Build the WASM bundle
# - target: no-modules (fits Service Workers and uses wasm_bindgen globals)
# - includes: SW runtime + user workload (EchoService)
wasm-pack build \
  --target no-modules \
  --out-dir "$OUT_DIR" \
  --out-name echo_server \
  --release

# Remove files that are not needed
rm -f "$OUT_DIR/package.json" "$OUT_DIR/.gitignore"

echo ""
echo "✅ WASM built successfully!"
echo ""
echo "📁 Output: $OUT_DIR"
echo ""
echo "Artifacts:"
echo "  - echo_server_bg.wasm  : main WASM payload (user code + SW runtime)"
echo "  - echo_server.js       : JS glue generated by wasm-bindgen"
echo "  - echo_server.d.ts     : TypeScript type definitions"
echo ""
echo "Files:"
ls -la "$OUT_DIR"/echo_server*

echo ""
echo "Next step:"
echo "   1. Start the dev server: cd .. && pnpm dev"
