//! Auto-generated Actor code
//! Service: UserService
//! Package: example.user.v1
//!
//! ⚠️  Do not edit this file

use wasm_bindgen::prelude::*;
use serde::{Serialize, Deserialize};

/// GetUserRequest message
#[derive(Debug, Clone, Serialize, Deserialize)]
#[wasm_bindgen]
pub struct GetUserRequest {
    pub user_id: String,
}

/// GetUserResponse message
#[derive(Debug, Clone, Serialize, Deserialize)]
#[wasm_bindgen]
pub struct GetUserResponse {
    pub user: User,
}

/// CreateUserRequest message
#[derive(Debug, Clone, Serialize, Deserialize)]
#[wasm_bindgen]
pub struct CreateUserRequest {
    pub name: String,
    pub email: String,
    pub age: Option<i32>,
    pub tags: Vec<String>,
}

/// CreateUserResponse message
#[derive(Debug, Clone, Serialize, Deserialize)]
#[wasm_bindgen]
pub struct CreateUserResponse {
    pub user: User,
}

/// UpdateUserRequest message
#[derive(Debug, Clone, Serialize, Deserialize)]
#[wasm_bindgen]
pub struct UpdateUserRequest {
    pub user_id: String,
    pub name: Option<String>,
    pub email: Option<String>,
    pub age: Option<i32>,
}

/// UpdateUserResponse message
#[derive(Debug, Clone, Serialize, Deserialize)]
#[wasm_bindgen]
pub struct UpdateUserResponse {
    pub user: User,
    pub updated: bool,
}

/// DeleteUserRequest message
#[derive(Debug, Clone, Serialize, Deserialize)]
#[wasm_bindgen]
pub struct DeleteUserRequest {
    pub user_id: String,
}

/// DeleteUserResponse message
#[derive(Debug, Clone, Serialize, Deserialize)]
#[wasm_bindgen]
pub struct DeleteUserResponse {
    pub deleted: bool,
}

/// ListUsersRequest message
#[derive(Debug, Clone, Serialize, Deserialize)]
#[wasm_bindgen]
pub struct ListUsersRequest {
    pub page: i32,
    pub page_size: i32,
    pub filter: Option<String>,
}

/// WatchUsersRequest message
#[derive(Debug, Clone, Serialize, Deserialize)]
#[wasm_bindgen]
pub struct WatchUsersRequest {
    pub user_ids: Vec<String>,
}

/// User message
#[derive(Debug, Clone, Serialize, Deserialize)]
#[wasm_bindgen]
pub struct User {
    pub id: String,
    pub name: String,
    pub email: String,
    pub age: i32,
    pub tags: Vec<String>,
    pub created_at: i64,
    pub updated_at: i64,
    pub is_active: bool,
}

/// UserEvent message
#[derive(Debug, Clone, Serialize, Deserialize)]
#[wasm_bindgen]
pub struct UserEvent {
    pub event_type: String,
    pub user: User,
    pub timestamp: i64,
}

/// UserService Actor
#[wasm_bindgen]
pub struct UserServiceActor {
    // Actor state
}

#[wasm_bindgen]
impl UserServiceActor {
    /// Construct a new Actor instance
    #[wasm_bindgen(constructor)]
    pub fn new() -> Self {
        Self {}
    }

    /// `GetUser` method
    pub async fn get_user(&self, request: GetUserRequest) -> Result<GetUserResponse, JsValue> {
        // TODO: implement the method logic
        todo!("Implement method: GetUser")
    }

    /// `CreateUser` method
    pub async fn create_user(&self, request: CreateUserRequest) -> Result<CreateUserResponse, JsValue> {
        // TODO: implement the method logic
        todo!("Implement method: CreateUser")
    }

    /// `UpdateUser` method
    pub async fn update_user(&self, request: UpdateUserRequest) -> Result<UpdateUserResponse, JsValue> {
        // TODO: implement the method logic
        todo!("Implement method: UpdateUser")
    }

    /// `DeleteUser` method
    pub async fn delete_user(&self, request: DeleteUserRequest) -> Result<DeleteUserResponse, JsValue> {
        // TODO: implement the method logic
        todo!("Implement method: DeleteUser")
    }

    /// `ListUsers` method (streaming)
    pub async fn list_users(&self, request: ListUsersRequest) -> Result<JsValue, JsValue> {
        // TODO: implement the streaming method
        todo!("Implement streaming method: ListUsers")
    }

    /// `WatchUsers` method (streaming)
    pub async fn watch_users(&self, request: WatchUsersRequest) -> Result<JsValue, JsValue> {
        // TODO: implement the streaming method
        todo!("Implement streaming method: WatchUsers")
    }

}
