name: CI (Python Codegen)

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    working-directory: tools/protoc-gen/python

jobs:
  build:
    name: Build & Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: tools/protoc-gen/python/pyproject.toml

      - name: Install package
        run: pip install -e .

      - name: Build package
        run: |
          python -m pip install -U build
          python -m build
