edition = 1
exports = []

[package]
name = "file-transfer-sender"
manufacturer = "acme"
type = "generic.GenericClient"
description = "File transfer sender using DataStream API"
authors = []

[dependencies]

[system.signaling]
url = "ws://127.0.0.1:8081/"

[system.deployment]
realm = 0

[system.discovery]
visible = true

[scripts]
dev = "cargo run"
test = "cargo test"
