[metadata]
version = 1
generated_at = "2026-01-10T06:06:28.862327+00:00"

[[dependency]]
name = "echo-real-server"
actr_type = "acme:EchoService"
fingerprint = "service_semantic:0d0d204d724cafc1cb8fd5d6f68ca683d9f6546c6e70deab75781a2f4230a755"
cached_at = "2026-01-10T06:06:28.862324+00:00"

[[dependency.files]]
path = "echo-real-server/echo.proto"
fingerprint = ""
